### ISSUE TITLE
AttributeError in autoupdate.py while csv import

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1935]
If you import many (e.g. 1000) items or users per csv file you get an AttributeError on server console like this while OpenSlides try to autoupdate each imported item/user:
```
[E 160202 22:46:53 ioloop:629] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fecb5761840>, HTTPResponse(_body=None,buffer=None,code=599,effective_url='http://localhost:8000/rest/agenda/item/706/',error=HTTPError(599, 'Timeout', None),headers=<tornado.httputil.HTTPHeaders object at 0x7fecb685a0b8>,reason='Unknown',request=<tornado.httpclient.HTTPRequest object at 0x7fecb6a3a1d0>,request_time=20.67912268638611,time_info={}))
    Traceback (most recent call last):
      File "/home/emanuel/projects/openslides/src/OpenSlides/.venv2/lib/python3.4/site-packages/tornado/ioloop.py", line 600, in _run_callback
        ret = callback()
      File "/home/emanuel/projects/openslides/src/OpenSlides/.venv2/lib/python3.4/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/autoupdate.py", line 88, in forward_rest_response
        'data': json.loads(response.body.decode())}
    AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by emanuelschuetze** [comment]
catch 500 errors
