### ISSUE TITLE
Whoosh and DB LockError while import of users

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2198]
Try to import 3 users (e.g. enter 3 lines in textarea or use a csv example).
Only 2 users are imprted. Server shows a lot of errors:

```
...
django.db.utils.OperationalError: database is locked
[2016/06/11 22:19:21] HTTP POST /rest/users/user/ 500 [1.18, 127.0.0.1:37592]
Internal Server Error: /rest/users/user/
...
whoosh.index.LockError
```

@ostcar Please look at this. It looks like a problem caused by big mode.

**Comment by ostcar** [comment]
There could be two different errors, one with whoosh and one with sqlite. I could only reproduce the one with whoosh.

Django Channels runserver command starts 4 worker threads. So even on the small mode, OpenSlides has to be multithread ready.

On the client side the user import sends different post-request to the server at the same time. So the server tries to create to create the users at the same time and tries to touch the sqlite database and the whoosh index for writing at the same time.

The whoosh problem was expected: https://github.com/OpenSlides/OpenSlides/blob/master/openslides/utils/search.py#L117

**Comment by emanuelschuetze** [comment]
You can see the the sqlite error if you scroll up in your server terminal output (comes before the whoosh error).
This symptom of users import (several write operations at one time) could also be happened if several admin users run different write actions in the same time. Right?

**Comment by emanuelschuetze** [comment]
@ostcar @normanjaeckel 
This issue is a blocker for use current master in production - and also for tests with many users/motions you always run into this lockerror. So we need a fix for this regression asap. Who can look a this issue?

**Comment by normanjaeckel** [comment]
Try this: http://whoosh.readthedocs.io/en/latest/api/writing.html#utility-writers

**Comment by normanjaeckel** [comment]
Please test again. The SQLite error might be still there.

**Comment by emanuelschuetze** [comment]
Successfully tested: The whoosh.index.LockError is fixed with PR #2251.

**Comment by emanuelschuetze** [comment]
Still open: the DB error `django.db.utils.OperationalError: database is locked`

Steps to reproduce:
Import users csv example file.

@normanjaeckel Any idea?

**Comment by ostcar** [comment]
https://docs.djangoproject.com/en/dev/ref/databases/#database-is-locked-errors

**Comment by emanuelschuetze** [comment]
@normanjaeckel Can you try a pull request?

**Comment by normanjaeckel** [comment]
```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(OPENSLIDES_USER_DATA_PATH, 'database.sqlite'),
        'OPTIONS': {
            'timeout': 600000
        }
    }
}
```
Try this but it does not fix the problem.

**Comment by ostcar** [comment]
I can not reproduce the sqlite error. It works fine on my computer. I read in the documentation of python-sqlite, sqlite and django but could not find anything why I works for me and not for you. @emanuelschuetze can you test this on different operating systems? Maybe it is a special problem with debian based distributions (maybe they use strange compile arguments for sqlite).

**Comment by emanuelschuetze** [comment]
@ostcar What were your steps to reproduce it? Please try my steps to reproduce it (I cannot imagine that it depends from the operation system):

Here my steps to reproduce it always on Ubuntu 16.04:
* remove `personal_data` directory (with DB, search index, settings etc.)
* run OpenSlides on current master: `python manage.py start` (new sqlite db is created)
* login and go to `/users/import`
* download the csv example and select this csv file (you see 4 example users in the preview)
* click button "Import 4 participants"
=> Only 3 of 4 participants are successfully imported. Server terminal shows errors:
`sqlite3.OperationalError: database is locked`

Full backtrace:
```
Internal Server Error: /rest/users/user/
Traceback (most recent call last):
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/channels/handler.py", line 227, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/mixins.py", line 26, in perform_create
    serializer.save()
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/serializers.py", line 191, in save
    self.instance = self.create(validated_data)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/users/serializers.py", line 103, in create
    return super().create(validated_data)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/serializers.py", line 867, in create
    setattr(instance, field_name, value)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 481, in __set__
    manager.set(value)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 910, in set
    self.add(*new_objs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 843, in add
    self._add_items(self.source_field_name, self.target_field_name, *objs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 1004, in _add_items
    for obj_id in new_ids
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/query.py", line 450, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/query.py", line 1056, in _batched_insert
    using=self.db)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked
```

**Comment by emanuelschuetze** [comment]
@normanjaeckel I tested the timeout option in settings.py - same error.

**Comment by ostcar** [comment]
This seems to be a problem with one of our requirements.

I did exactly what you ask and did not get an error. Then I run ```pip install -r requirements.txt -U``` and now I get the database is locked error.

Here are the packages, that where updated:
```
Installing collected packages: Django, beautifulsoup4, asgiref, autobahn, daphne, channels, webencodings, setuptools, html5lib, coverage, mccabe, flake8, pillow, tornado
  Found existing installation: Django 1.9.7
    Uninstalling Django-1.9.7:
      Successfully uninstalled Django-1.9.7
  Found existing installation: beautifulsoup4 4.4.1
    Uninstalling beautifulsoup4-4.4.1:
      Successfully uninstalled beautifulsoup4-4.4.1
  Found existing installation: asgiref 0.13.3
    Uninstalling asgiref-0.13.3:
      Successfully uninstalled asgiref-0.13.3
  Found existing installation: autobahn 0.14.1
    Uninstalling autobahn-0.14.1:
      Successfully uninstalled autobahn-0.14.1
  Found existing installation: daphne 0.13.0
    Uninstalling daphne-0.13.0:
      Successfully uninstalled daphne-0.13.0
  Found existing installation: channels 0.15.0
    Uninstalling channels-0.15.0:
      Successfully uninstalled channels-0.15.0
  Found existing installation: setuptools 23.1.0
    Uninstalling setuptools-23.1.0:
      Successfully uninstalled setuptools-23.1.0
  Found existing installation: html5lib 0.9999999
    Uninstalling html5lib-0.9999999:
      Successfully uninstalled html5lib-0.9999999
  Found existing installation: coverage 4.1
    Uninstalling coverage-4.1:
      Successfully uninstalled coverage-4.1
  Found existing installation: mccabe 0.5.0
    Uninstalling mccabe-0.5.0:
      Successfully uninstalled mccabe-0.5.0
  Found existing installation: flake8 2.6.2
    Uninstalling flake8-2.6.2:
      Successfully uninstalled flake8-2.6.2
  Found existing installation: Pillow 3.2.0
    Uninstalling Pillow-3.2.0:
      Successfully uninstalled Pillow-3.2.0
  Found existing installation: tornado 4.3
    Uninstalling tornado-4.3:
      Successfully uninstalled tornado-4.3
Successfully installed Django-1.9.9 asgiref-0.14.0 autobahn-0.15.0 beautifulsoup4-4.5.1 channels-0.17.2 coverage-4.2 daphne-0.14.3 flake8-3.0.4 html5lib-0.999999999 mccabe-0.5.2 pillow-3.3.0 setuptools-25.1.6 tornado-4.4.1 webencodings-0.5
```

**Comment by ostcar** [comment]
So to fix this we have to find the problematic dependency, downgrade it and write a bug report.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Please try to find the problematic python package (and version). Thx.

**Comment by FinnStutzenstein** [comment]
I have checked all packages alone, so all other packages are the newest ones. I get the Error every time, it seems to be a combination of packages, that causes this error. My workflow:
```
rm -rf peronal_data/
pip install -r requirements.txt -U //Update the last package to the newest version
pip uninstall -v django
pip install -v django==1.9.7
python manage.py start --no-browser --host 192.168.46.10 --port 9999
//testing to import the example.csv
```
I had problems with beautifulsoap4. While uninstalling I have got this error:
`Cannot uninstall requirement beautifulsoap4, not installed` So, the error **_may_** come from beautifulsoap4 - I will try to check this.

Now I am going to downgrade all mentioned packages to check, whether I can get rid of the this error and try to upgrade each package at once, hoping to find the right package/combination.

**Comment by FinnStutzenstein** [comment]
@ostcar I could not recreate your status where no error appeared. I have the following packages and versions matching yours:
```
$ pip freeze
asgiref==0.13.3
autobahn==0.14.1
backports-abc==0.4
beautifulsoup4==4.5.1
channels==0.15.0
coverage==4.1
daphne==0.13.0
Django==1.9.7
djangorestframework==3.3.3
flake8==2.6.2
html5lib==0.9999999
isort==4.2.5
jsonfield==1.0.3
mccabe==0.5.0
natsort==4.0.4
Pillow==3.2.0
pycodestyle==2.0.0
pyflakes==1.2.3
PyPDF2==1.25.1
reportlab==3.3.0
roman==2.0.0
six==1.10.0
sockjs-tornado==1.0.3
tornado==4.3
Twisted==16.2.0
txaio==2.5.1
webencodings==0.5
Whoosh==2.7.4
zope.interface==4.2.0
```
Maybe you have overseen something? Emanuel said like an older databaseversion or so.

**Comment by ostcar** [comment]
I don't get a working version now neither. At least I can reproduce the error now...

**Comment by ostcar** [comment]
See https://github.com/andrewgodwin/channels/pull/297
