### ISSUE TITLE
Unable to start OpenSlides in Debian 8.5

### ISSUE THREAD

**Issue by j4nkr** [OpenSlides/OpenSlides#2229]
Unfortunately i'am not able to start OpenSlides after a successfully installation in Debian 8.5. 
```{r, engine='bash', count_lines}
jk@debtest:~$ openslides 
Traceback (most recent call last):
  File "/usr/local/bin/openslides", line 9, in <module>
    load_entry_point('openslides==2.0.1-dev', 'console_scripts', 'openslides')()
  File "/usr/local/lib/python2.7/dist-packages/openslides-2.0.1_dev-py2.7.egg/openslides/__main__.py", line 25, in main
    parser = get_parser()
  File "/usr/local/lib/python2.7/dist-packages/openslides-2.0.1_dev-py2.7.egg/openslides/__main__.py", line 150, in get_parser
    help_text))
TypeError: __init__() takes exactly 3 arguments (4 given)
```
Same error with root, tried to install via pip and build from github sources.
Installed python packages:
```{r, engine='bash', count_lines}
jk@debtest:~$ apt list --installed | grep python

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

dh-python/stable,now 1.20141111-2 all  [Installiert,automatisch]
libpython-dev/stable,now 2.7.9-1 amd64 [installiert,automatisch-entfernbar]
libpython-stdlib/stable,now 2.7.9-1 amd64  [Installiert,automatisch]
libpython2.7/stable,now 2.7.9-2 amd64 [installiert,automatisch-entfernbar]
libpython2.7-dev/stable,now 2.7.9-2 amd64 [installiert,automatisch-entfernbar]
libpython2.7-minimal/stable,now 2.7.9-2 amd64  [Installiert,automatisch]
libpython2.7-stdlib/stable,now 2.7.9-2 amd64  [Installiert,automatisch]
libpython3-dev/stable,now 3.4.2-2 amd64  [Installiert,automatisch]
libpython3-stdlib/stable,now 3.4.2-2 amd64  [Installiert,automatisch]
libpython3.4/stable,now 3.4.2-1 amd64  [Installiert,automatisch]
libpython3.4-dev/stable,now 3.4.2-1 amd64  [Installiert,automatisch]
libpython3.4-minimal/stable,now 3.4.2-1 amd64  [Installiert,automatisch]
libpython3.4-stdlib/stable,now 3.4.2-1 amd64  [Installiert,automatisch]
python/stable,now 2.7.9-1 amd64  [installiert]
python-apt/stable,now 0.9.3.12 amd64  [installiert]
python-apt-common/stable,now 0.9.3.12 all  [Installiert,automatisch]
python-blinker/stable,now 1.3.dfsg2-1 all  [Installiert,automatisch]
python-cffi/stable,now 0.8.6-1 amd64  [Installiert,automatisch]
python-chardet/stable,now 2.3.0-1 all  [Installiert,automatisch]
python-colorama/stable,now 0.3.2-1 all  [Installiert,automatisch]
python-cryptography/stable,now 0.6.1-1 amd64  [Installiert,automatisch]
python-debian/stable,now 0.1.27 all  [Installiert,automatisch]
python-debianbts/stable,now 1.12 all  [Installiert,automatisch]
python-defusedxml/stable,now 0.4.1-2 all  [Installiert,automatisch]
python-distlib/stable,now 0.1.9-1 all  [Installiert,automatisch]
python-docutils/stable,now 0.12+dfsg-1 all  [Installiert,automatisch]
python-flask/stable,now 0.10.1-2 all  [Installiert,automatisch]
python-html5lib/stable,now 0.999-3 all  [Installiert,automatisch]
python-itsdangerous/stable,now 0.24+dfsg1-1 all  [Installiert,automatisch]
python-jinja2/stable,now 2.7.3-1 all  [Installiert,automatisch]
python-markupsafe/stable,now 0.23-1+b1 amd64  [Installiert,automatisch]
python-minimal/stable,now 2.7.9-1 amd64  [installiert]
python-ndg-httpsclient/stable,now 0.3.2-1 all  [Installiert,automatisch]
python-openslide-examples/stable,now 1.0.1-5 all  [Installiert,automatisch]
python-openssl/stable,now 0.14-1 all  [Installiert,automatisch]
python-pil/stable,stable,now 2.6.1-2+deb8u2 amd64  [Installiert,automatisch]
python-pip/stable,now 1.5.6-5 all  [installiert]
python-pkg-resources/stable,now 5.5.1-1 all  [Installiert,automatisch]
python-ply/stable,now 3.4-5 all  [Installiert,automatisch]
python-pyasn1/stable,now 0.1.7-1 all  [Installiert,automatisch]
python-pycparser/stable,now 2.10+dfsg-3 all  [Installiert,automatisch]
python-pygments/stable,stable,now 2.0.1+dfsg-1.1+deb8u1 all  [Installiert,automatisch]
python-pyinotify/stable,now 0.9.4-1 all  [Installiert,automatisch]
python-reportbug/stable,now 6.6.3 all  [installiert]
python-requests/stable,now 2.4.3-6 all  [Installiert,automatisch]
python-roman/stable,now 2.0.0-1 all  [Installiert,automatisch]
python-setuptools/stable,now 5.5.1-1 all  [Installiert,automatisch]
python-six/stable,now 1.8.0-1 all  [Installiert,automatisch]
python-soappy/stable,now 0.12.22-1 all  [Installiert,automatisch]
python-support/stable,now 1.0.15 all  [installiert]
python-urllib3/stable,now 1.9.1-3 all  [Installiert,automatisch]
python-werkzeug/stable,now 0.9.6+dfsg-1 all  [Installiert,automatisch]
python-wheel/stable,now 0.24.0-1 all  [Installiert,automatisch]
python-wstools/stable,now 0.4.3-2 all  [Installiert,automatisch]
python2.7/stable,now 2.7.9-2 amd64  [installiert]
python2.7-dev/stable,now 2.7.9-2 amd64 [installiert,automatisch-entfernbar]
python2.7-minimal/stable,now 2.7.9-2 amd64  [Installiert,automatisch]
python3/stable,now 3.4.2-2 amd64  [Installiert,automatisch]
python3-dev/stable,now 3.4.2-2 amd64  [installiert]
python3-minimal/stable,now 3.4.2-2 amd64  [Installiert,automatisch]
python3-openslide/stable,now 1.0.1-5 all  [installiert]
python3-pil/stable,stable,now 2.6.1-2+deb8u2 amd64  [Installiert,automatisch]
python3.4/stable,now 3.4.2-1 amd64  [Installiert,automatisch]
python3.4-dev/stable,now 3.4.2-1 amd64  [Installiert,automatisch]
python3.4-minimal/stable,now 3.4.2-1 amd64  [Installiert,automatisch]
```

**Comment by emanuelschuetze** [comment]
You have to use python 3.4+, see [README](https://github.com/OpenSlides/OpenSlides#a-check-requirements).

**Comment by j4nkr** [comment]
Thanks and sorry ...
