### ISSUE TITLE
'manage.py start' fails on computers without a browser

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2249]
When running `manage.py start`, it do not start the webserver if no runnable browser is found while giving this error:

```
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    exit(main())
  File "/home/finn/OpenSlides/OpenSlides/openslides/__main__.py", line 41, in main
    known_args.callback(known_args)
  File "/home/finn/OpenSlides/OpenSlides/openslides/__main__.py", line 182, in start
    start_browser('http://localhost:%s' % args.port)
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/main.py", line 264, in start_browser
    browser = webbrowser.get()
  File "/usr/lib/python3.4/webbrowser.py", line 51, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser
```
This happend to me on a remote server with only a console.

Maybe simple solution: Catch error, skip the start and maybe give a message on the console.

**Comment by matakuka** [comment]
you can start it by `python managy.py start --no-browser`.

**Comment by emanuelschuetze** [comment]
The start command should not abort if no browser is available. So catching error and start server (without running browser) would be a good idea. 
And yes, of course, you could use `--no-browser` directly.
@FinnStutzenstein Feel free to make a pull request for this issue.
