### ISSUE TITLE
Can't create database with django 1.10.1

### ISSUE THREAD

**Issue by salevajo** [OpenSlides/OpenSlides#2354]
Tried to create a superuser in an Ubuntu and in a macOS environment getting this exception:

(.virtualenv) asterix:OpenSlides pingus$ python manage.py createsuperuser
Traceback (most recent call last):
  File "/Users/pingus/Documents/Projects/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/contrib/auth/hashers.py", line 129, in get_hasher
    return hashers[algorithm]
KeyError: 'md5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    exit(main())
  File "/Users/pingus/Documents/Projects/OpenSlides/openslides/__main__.py", line 37, in main
    execute_from_command_line(sys.argv)
  File "/Users/pingus/Documents/Projects/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/pingus/Documents/Projects/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/pingus/Documents/Projects/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/pingus/Documents/Projects/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/pingus/Documents/Projects/OpenSlides/openslides/users/management/commands/createsuperuser.py", line 13, in handle
    created = User.objects.create_or_reset_admin_user()
  File "/Users/pingus/Documents/Projects/OpenSlides/openslides/users/models.py", line 49, in create_or_reset_admin_user
    admin.password = make_password(admin.default_password, '', 'md5')
  File "/Users/pingus/Documents/Projects/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/contrib/auth/hashers.py", line 79, in make_password
    hasher = get_hasher(hasher)
  File "/Users/pingus/Documents/Projects/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/contrib/auth/hashers.py", line 133, in get_hasher
    "setting?" % algorithm)
ValueError: Unknown password hashing algorithm 'md5'. Did you specify it in the PASSWORD_HASHERS setting?

Additional version infos:

(.virtualenv) asterix:OpenSlides pingus$ python --version
Python 3.5.2
(.virtualenv) asterix:OpenSlides pingus$ pip --version
pip 8.1.1 from /Users/pingus/Documents/Projects/OpenSlides/.virtualenv/lib/python3.5/site-packages (python 3.5)
(.virtualenv) asterix:OpenSlides pingus$ node --version
v6.5.0
(.virtualenv) asterix:OpenSlides pingus$ npm --version
3.10.3

**Comment by normanjaeckel** [comment]
In Django 1.10.x they removed our `MD5PasswordHasher`. We have to readd it to global settings. https://docs.djangoproject.com/en/1.10/ref/settings/#password-hashers

**Comment by emanuelschuetze** [comment]
This issue is very urgent: You can't create a new database with current master because django 1.10.1 is installed by default!
@normanjaeckel Can you make a pullrequest please?

Workaround:  Install Django 1.9.9 manually (`pip install django==1.9.9`) and then start and create db (`python manage.py start`)
