### ISSUE TITLE
Scrolling and zooming in projector view broken

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2547]
This is for me a release blocker bug.

Take for example a motion with about 30 lines. Of course not all 30 lines fit to the projector screen. Therefore OS has the feature to scroll in the projector view. Unfortunately in OS 2.1dev this feature is broken. I can press the scroll and zoom buttons but nothing happens, not in the projector preview nor in the projector.

**Comment by FinnStutzenstein** [comment]
I get an error, too:

```
Internal Server Error: /rest/core/projector/1/control_view/
Traceback (most recent call last):
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/handler.py", line 227, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
    response = self.handle_exception(exc)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/views.py", line 434, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/finn/OpenSlides/OpenSlides/openslides/core/views.py", line 439, in control_view
    projector_instance.save()
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/models.py", line 76, in save
    inform_changed_data(self.get_root_rest_element(), information=information)
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/autoupdate.py", line 163, in inform_changed_data
    information=information))
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/collection.py", line 15, in from_instance
    return cls(instance=instance, deleted=deleted, information=information)
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/collection.py", line 62, in __init__
    self.save_to_cache()
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/collection.py", line 222, in save_to_cache
    cache.set(self.get_cache_key(), self.get_full_data())
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/collection.py", line 189, in get_full_data
    self.full_data = self.get_access_permissions().get_full_data(self.get_instance())
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/access_permissions.py", line 57, in get_full_data
    return self.get_serializer_class(user=None)(instance).data
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/serializers.py", line 508, in data
    ret = super(Serializer, self).data
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/serializers.py", line 240, in data
    self._data = self.to_representation(self.instance)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/serializers.py", line 477, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/fields.py", line 861, in to_representation
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'CombinedExpression'
```

@ostcar may have a look at this; it seems that the problem is in the new cache/autoupdatesystem...

**Comment by normanjaeckel** [comment]
The problem is the F() query in the projector (control) view

**Comment by emanuelschuetze** [comment]
This is a Blocker dir iur 2.1 (beta1) Release! 

@FinnStutzenstein  do you have any idea for a fix?

**Comment by FinnStutzenstein** [comment]
referring to [F-expressions](https://docs.djangoproject.com/en/1.7/ref/models/queries/#f-expressions) one could write (I didn't test this..)
```
 projector_instance.scale = projector_instance.scale + 1
projector_instance.save()
```
@normanjaeckel Should the OS cache support `CombinedExpressions` (like `F()`) or stick with the code above to avoid these expressions, so that the cache could handle this? Avoiding seems to be the easiest solution..

**Comment by normanjaeckel** [comment]
@ostcar is the expert of the cache. If we avoid using F-expression we have to add a transaction at least.

**Comment by emanuelschuetze** [comment]
@ostcar Ping. This issue is very important and a blocker for upcoming 2.1-beta1. Can you please look this issue please? Thanks!

**Comment by emanuelschuetze** [comment]
This problem was introduces with caching commit 368873e (maybe it is a similar problem as #2597 and #2541?)

**Comment by donovaly** [comment]
Many thanks, I can verify the fix.
