### ISSUE TITLE
OS 2.1: CSV-Import of motions is broken

### ISSUE THREAD

**Issue by CatoTH** [OpenSlides/OpenSlides#2644]
Importing the sample CSV file from https://github.com/OpenSlides/OpenSlides/wiki/CSV-Import does not work at the moment. Each motion is imported using a single request, all of them at the same time. Only the first one succeeds: for all further motions the following "database is locked"-error message is thrown in the console:

```
[2016/11/18 21:10:50] HTTP POST /rest/motions/motion/ 500 [0.65, 127.0.0.1:64729]
Internal Server Error: /rest/motions/motion/
Traceback (most recent call last):
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/channels/handler.py", line 227, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
    response = self.handle_exception(exc)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/rest_framework/views.py", line 434, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/tobiashossl/Sites/OpenSlides/openslides/motions/views.py", line 106, in create
    motion = serializer.save(request_user=request.user)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/rest_framework/serializers.py", line 192, in save
    self.instance = self.create(validated_data)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/Users/tobiashossl/Sites/OpenSlides/openslides/motions/serializers.py", line 321, in create
    motion.save()
  File "/Users/tobiashossl/Sites/OpenSlides/openslides/motions/models.py", line 230, in save
    super(Motion, self).save(skip_autoupdate=True, *args, **kwargs)
  File "/Users/tobiashossl/Sites/OpenSlides/openslides/utils/models.py", line 74, in save
    return_value = super().save(*args, **kwargs)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/tobiashossl/Sites/OpenSlides/.virtualenv/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked
```

This problem does not occur in v2.0.

**Comment by emanuelschuetze** [comment]
Please verifiy that you have installed the latest requirements (`pip install -U -r requirements.txt`).  Looks  that you have not installed the last channels release.

So please try to reproduce with fresh database/settings with current master.

**Comment by emanuelschuetze** [comment]
BTW: Use the demo csv file which can be downloaded from the motion import view.

**Comment by CatoTH** [comment]
Ok, seems like thie pip-command really did solve the problem. Sorry for the disturbance then..
(I have another problem, though... see other issue)
