### ISSUE TITLE
motion line numbering for pdfmake: "TypeError: Cannot read property 'indexOf' of null"

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2770]
Failure while generating a motion pdf via pdfmake:
```
angular.js:13920 TypeError: Cannot read property 'indexOf' of null
    at extractLineNumbers (http://localhost:8000/static/js/openslides.js:4556:92)
    at extractLineNumbers (http://localhost:8000/static/js/openslides.js:4563:82)
    at extractLineNumbers (http://localhost:8000/static/js/openslides.js:4563:82)
    at extractLineNumbers (http://localhost:8000/static/js/openslides.js:4563:82)
    at ParseElement (http://localhost:8000/static/js/openslides.js:4863:53)
    at http://localhost:8000/static/js/openslides.js:4914:33
    at Array.forEach (native)
    at ParseHtml (http://localhost:8000/static/js/openslides.js:4913:41)
    at Object.convertHTML (http://localhost:8000/static/js/openslides.js:4918:21)
    at motionText (http://localhost:8000/static/js/openslides.js:10945:34)
```

The mention code line in `extractLineNumbers` function:
```
if (element.nodeName == 'SPAN' && element.getAttribute('class').indexOf('os-line-number') > -1) {
```

I can reproduce this failure with an old database only. So if there is a fix I can test it.
@CatoTH Any idea how we can prevent this error?

**Comment by tsiegleauq** [comment]
To translate this error:
`if (element.nodeName == 'SPAN' && element.getAttribute('class').indexOf('os-line-number') > -1) {
`

If tere is any SPAN-element "**without**" the information "os-line-number", you will receive this error.
A SPAN-element without os-line-number attribute can (currently) only by a styled text (like red text background for example).
We simply need to check if the span is a part of the line-numbering process.

During PDF generation we do it like this:
`if (element.getAttribute("data-line-number")) { ... }`

**Comment by CatoTH** [comment]
I created a fix for this problem: https://github.com/OpenSlides/OpenSlides/pull/2776

**Comment by emanuelschuetze** [comment]
fixed.
