### ISSUE TITLE
Current daphne needs current twisted

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#2829]
Currently we pin twisted to an older version in the requirements_production.txt: https://github.com/OpenSlides/OpenSlides/blob/master/requirements_production.txt#L9

But this does not work with daphne 1.0.1 which is installed with ```pip install -r requirements.txt```

If you use daphne 1.0.1 with twisted 16.3.2, then you get the following error and daphne does not start at all (even when the message tells you differently) 
```
python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
January 10, 2017 - 19:50:25
Django version 1.10.5, using settings 'settings'
Starting Channels development server at http://127.0.0.1:8000/
Channel layer default (asgi_redis.core.RedisChannelLayer)
Quit the server with CONTROL-C.
2017-01-10 19:50:25,915 - INFO - worker - Listening on channels autoupdate.send_data, http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-01-10 19:50:25,916 - INFO - worker - Listening on channels autoupdate.send_data, http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-01-10 19:50:25,918 - INFO - worker - Listening on channels autoupdate.send_data, http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-01-10 19:50:25,921 - INFO - worker - Listening on channels autoupdate.send_data, http.request, websocket.connect, websocket.disconnect, websocket.receive
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f4c761c7950>
Traceback (most recent call last):
  File "/home/ossi/.virtualenvs/openslides/lib/python3.6/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/ossi/.virtualenvs/openslides/lib/python3.6/site-packages/channels/management/commands/runserver.py", line 84, in inner_run
    ws_protocols=getattr(settings, 'CHANNELS_WS_PROTOCOLS', None),
  File "/home/ossi/.virtualenvs/openslides/lib/python3.6/site-packages/daphne/server.py", line 41, in __init__
    ''' % self.__class__.__name__)
DeprecationWarning: 
                The host/port/unix_socket/file_descriptor keyword arguments to Server are deprecated.
```

Installing the current version of twisted fixes the problem.

Please do not solve this problem by fixing the version of daphne. And if you have to, then please also fix the current version of channels, asgi_ref and asgi_redis

**Comment by normanjaeckel** [comment]
Maybe you have to install current channels version. I tested Twisted==16.3.2 channels==1.0.1 daphne==1.0.1 successfully.

**Comment by eknoes** [comment]
Can confirm the channels update, had the same problem. Update to newest channels version.#2834 fixed it!
