### ISSUE TITLE
Error after changing group permission from plugin: MultipleObjectsReturned: get() returned more than one Permission

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2901]
Reproduceable with current master and openslides-votecollector plugin 2.0.0:
* Start OpenSlides with fresh personal_data dir
* Add "openslides_votecollector" to settings.py
* Restart OpenSlides
* Go to permission matrix and deselect/select the VoteCollector can_manage permission for staff group. Error: **django.contrib.auth.models.MultipleObjectsReturned: get() returned more than one Permission -- it returned 2!**

@normanjaeckel Any idea?

```
Internal Server Error: /rest/users/group/3/
Traceback (most recent call last):
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/channels/handler.py", line 237, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
    response = self.handle_exception(exc)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/views.py", line 434, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/mixins.py", line 69, in update
    serializer.is_valid(raise_exception=True)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/serializers.py", line 214, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/serializers.py", line 408, in run_validation
    value = self.to_internal_value(data)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/serializers.py", line 438, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/fields.py", line 490, in run_validation
    value = self.to_internal_value(data)
  File "/home/emanuel/projdjango.contrib.auth.models.MultipleObjectsReturned: get() returned more than one Permission -- it returned 2!ects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/relations.py", line 483, in to_internal_value
    for item in data
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/relations.py", line 483, in <listcomp>
    for item in data
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/users/serializers.py", line 114, in to_internal_value
    permission = Permission.objects.get(content_type__app_label=app_label, codename=codename)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/query.py", line 389, in get
    (self.model._meta.object_name, num)
django.contrib.auth.models.MultipleObjectsReturned: get() returned more than one Permission -- it returned 2!
```

**Comment by normanjaeckel** [comment]
The plugin is broken. It defines the permission twice. Once in https://github.com/OpenSlides/openslides-votecollector/blob/2.0.0/openslides_votecollector/models.py#L46 and once in https://github.com/OpenSlides/openslides-votecollector/blob/2.0.0/openslides_votecollector/models.py#L104.

This is not an OpenSlides issue.
