### ISSUE TITLE
Changing things after deleting connected users failed (openslides.users.models.DoesNotExist)

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2904]
* Start OpenSlides with a fresh db.
* Create a motion as "admin".
* Create new staff user "test".
* Login as "test".
* Remove user "admin".
* Go to motion (which has no submitter, now)
* Try to change the motion state. => Error: **"openslides.users.models.DoesNotExist: User matching query does not exist."** - Motion is not changed.
Get Response: "{"detail":"Sie dürfen den Antragsstatus nicht auf 2 setzen."}"

```
Traceback (most recent call last):
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/autoupdate.py", line 129, in send_data
    output = collection_elements.as_autoupdate_for_user(user)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/collection.py", line 265, in as_autoupdate_for_user
    result.append(element.as_autoupdate_for_user(user))
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/collection.py", line 123, in as_autoupdate_for_user
    user)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/collection.py", line 108, in as_autoupdate
    *args)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/motions/access_permissions.py", line 44, in get_restricted_data
    is_submitter = user.get_full_data()['id'] in full_data.get('submitters_id', [])
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/collection.py", line 193, in get_full_data
    self.full_data = self.get_access_permissions().get_full_data(self.get_instance())
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/collection.py", line 168, in get_instance
    self.instance = query.get(pk=self.id)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
openslides.users.models.DoesNotExist: User matching query does not exist.
```

**Comment by normanjaeckel** [comment]
It is a problem of the websocket_user_cache and has nothing to do with supporters:
- Start with a fresh db and login as admin
- Create a new user "test"
- Open a private browser tab and login as test. Websocket connection is established
- Switch to admin browser
- Remove user test -> Nothing happens in the second browser. The websocket connection is still established.
- Now made some changes with admin (create a motion, change state or whatever public data change you like) -> The error occurs, because OpenSlides tries to serialize the changed object for the deleted user.

Solution: We have to do something if a user is deleted: Force open browsers of this user to reload and at least disconnect their websockets on server side or at least remove them from the cache.

@ostcar Any idea how to solve this in a smart way?
