### ISSUE TITLE
deleting files doesn't really delete them

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3146]
- add a file via the Files menu
- delete the file

result: OS tells you that the file was successfully deleted but it is still in the folder
~\openslides\media\file

**Comment by emanuelschuetze** [comment]
Right, I can confirm this.

@normanjaeckel This is a server issue. Why a mediafile is not deleted on file system?
I think, this is still important for 2.1! Can you  make a fix today?

**Comment by normanjaeckel** [comment]
This is a very old problem. I will see ...

**Comment by donovaly** [comment]
Please reopen, this bug is not fixed for all cases. It works now for image files but not for PDF files. Deleting an uploaded PDF does not nothing - it is kept in OS and on the harddisk.

**Comment by emanuelschuetze** [comment]
Sorry, but I can't confirm this with 2.1. All uploaded files can be deleted (from OS AND hardisk). Please try again with a fresh 2.1 installation/database.

**Comment by donovaly** [comment]
> Sorry, but I can't confirm this with 2.1. All uploaded files can be deleted (from OS AND hardisk). Please try again with a fresh 2.1 installation/database.

I used a virgin installation. Now I went even further and run the final OS 2.1 portable on a Win 7 (64bit) PC that has never seen OS before. I get the same result: all file types can be deleted, but not PDF files. They remain on the harddisk and even in OS. I tried all possible PDFs (single page. multi-page, encrypted etc.)

**Comment by emanuelschuetze** [comment]
I can't confim it. I retested it with 2.1-portable under Windows 10. PNG and PDF files are successfully deleted. Can you send me your pdf files? Is there something error output on Server console or in Browser JS console (press F12)?

**Comment by FinnStutzenstein** [comment]
Just fyi: My pdfs got deleted, too..

**Comment by donovaly** [comment]
Ah, one must try to dele several times until it works:
- virgin portable system on Windows 7 (64bit), Firefox 52.0.1 (64bit)
- upload a PDF of your choice

Only for the first PDF one adds one get this warning in the console:

[2017/04/04 12:07:51] HTTP GET /static/css/chosen-sprite.png 200 [0.01, 127.0.0.1:50811]
PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will be corrected. [pdf.py:1736]
[2017/04/04 12:08:07] HTTP POST /rest/mediafiles/mediafile/ 201 [0.15, 127.0.0.1:50811]

- project the PDF
- unproject the PDF
- delete the PDF

result: the confirmation dialog pops up. Clicking OK but then nothing happens, the file is not edeleted in OS and therefore also not from the harddisk

This is the console output:
[2017/04/04 12:13:16] HTTP POST /rest/core/projector/1/prune_elements/ 200 [0.06, 127.0.0.1:50877]
[2017/04/04 12:13:16] HTTP GET /media/file/Rk_3D_bei_444nH.pdf 200 [0.01, 127.0.0.1:50877]
[2017/04/04 12:13:16] HTTP GET /media/file/Rk_3D_bei_444nH.pdf 200 [0.02, 127.0.0.1:50881]
[2017/04/04 12:13:19] HTTP POST /rest/core/projector/1/clear_elements/ 200 [0.04, 127.0.0.1:50877]
[2017/04/04 12:13:24] HTTP DELETE /rest/mediafiles/mediafile/4/ 500 [0.05, 127.0.0.1:50881]

- now just repeat to delete the PDF

result: sometimes, but not always the deletion works; sometimes it won't work even after many times, then

- logout from OS (keep the server running
- log in again as admin
- delete the PDF

result: now deletion of all uploaded PDF works, except of the first uploaded PDF

- log out, stop the server
- restart the server, log in as admin

result: the first PDF can still not be deleted.

Don't get me wrong, the deletion from the harddisk works, but if the deletion in OS fails the deletion from the harddisks fails of course too.

**Comment by emanuelschuetze** [comment]
> [2017/04/04 12:13:24] HTTP DELETE /rest/mediafiles/mediafile/4/ 500 [0.05, 127.0.0.1:50881]

Interesting, you get a server error (500). Please set `DEBUG = True` in openslides\settings.py and restart OpenSlides. Then reproduce this error again and paste the server console output. Thx.

**Comment by donovaly** [comment]
At first I get again this already mentioned warning:
PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will be corrected. [pdf.py:1736]

When deleting the file I get:

[2017/04/05 18:27:19] HTTP GET /media/file/Telefonliste_neu.pdf 200 [0.02, 127.0.0.1:52705]
Internal Server Error: /rest/mediafiles/mediafile/9/
Traceback (most recent call last):
  File "C:\Download\openslides\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = get_response(request)
  File "C:\Download\openslides\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Download\openslides\lib\site-packages\channels\handler.py", line 237, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "C:\Download\openslides\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Download\openslides\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Download\openslides\lib\site-packages\rest_framework\viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Download\openslides\lib\site-packages\rest_framework\views.py", line 474, in dispatch
    response = self.handle_exception(exc)
  File "C:\Download\openslides\lib\site-packages\rest_framework\views.py", line 434, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Download\openslides\lib\site-packages\rest_framework\views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Download\openslides\lib\site-packages\openslides\mediafiles\views.py", line 67, in destroy
    mediafile.mediafile.storage.delete(mediafile.mediafile.name)
  File "C:\Download\openslides\lib\site-packages\django\core\files\storage.py", line 388, in delete
    os.remove(name)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Download\\openslides\\openslides\\media\\file\\10038239.PDF'
[2017/04/05 18:27:22] HTTP DELETE /rest/mediafiles/mediafile/9/ 500 [0.12, 127.0.0.1:52706]

On my private PC I have no virus scanner installed, so i wonder what process might access the PDF. To me it seems that displaying the PDF in OS triggers a process that keeps the PDF locked.

However, milestone 2.1.1 is not necessary.

**Comment by FinnStutzenstein** [comment]
Do you have multiple workers running?

**Comment by emanuelschuetze** [comment]
I can reproduce it with windows portable 2.1.1: 
Restart of browser and server helps. Then I can successfully delete the pdf file. Strange...

**Comment by donovaly** [comment]
> Do you have multiple workers running?

No.

It is probable that the bug is in a third-party application and not OS itself. nevertheless the PdfReadWarning should not occur. Perhaps fixing this also fixes the problem.

**Comment by emanuelschuetze** [comment]
I'll try to reproduce it again on windows portable...

**Comment by donovaly** [comment]
This works now correct in OS 2.2b1 -> closing
