### ISSUE TITLE
Category numbering fails

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3315]
To reproduce:

- Two categories: a, b
- Set in config 'identifier': 'set it manually'
- Three motions: A001, A002, A003 with identifiers 'a 1', 'a 2', 'a 3'
- But motions A001 and A003 into category a and motion A002 into category b
- Goto category a and click on numbering.
```
Internal Server Error: /rest/motions/category/1/numbering/
Traceback (most recent call last):
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: motions_motion.identifier

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/finn/OpenSlides/OpenSlides/openslides/motions/models.py", line 234, in save
    super(Motion, self).save(skip_autoupdate=True, *args, **kwargs)
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/models.py", line 78, in save
    return_value = super().save(*args, **kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/base.py", line 889, in _save_table
    forced_update)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/base.py", line 939, in _do_update
    return filtered._update(values) > 0
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/query.py", line 654, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1148, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: motions_motion.identifier

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/handler.py", line 240, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
    response = self.handle_exception(exc)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/views.py", line 434, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/finn/OpenSlides/OpenSlides/openslides/motions/views.py", line 557, in numbering
    motion.save(skip_autoupdate=True)
  File "/home/finn/OpenSlides/OpenSlides/openslides/motions/models.py", line 239, in save
    self._identifier_prefix,
AttributeError: 'Motion' object has no attribute '_identifier_prefix'
```
The [attribute error raised here](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/models.py#L239) is causing the issue. I think, OpenSlides tries to rename the identifier 'a 3' into 'a 2', but a motion with this identifier exists already. @normanjaeckel Can you investigate some more here?

**Comment by FinnStutzenstein** [comment]
Ok, with PR #3318 we do have now an error message informing the user, what the problem is.

We may give the user some options:

- Cancel, let the user change the identifiers manually.
- Force the numbering by setting blocking identifiers to temporary ones (or clear them)
- ... Any other ideas?

The main issue is that the manual changing is ok for a few motions, but I have seen cases, where are over a hundred identifiers to change.

If you have the problem with just two categories and moving motions from one to another, you can force the numbering on the first category and then numbering the second category again to include the invalid identifiers. This would be a nice solution. Are there situations, where this might fail?

**Comment by normanjaeckel** [comment]
I do not have any idea for a proper auto-fix at the moment so I propose to merge #3318.

**Comment by emanuelschuetze** [comment]
Reopened, see #3318.

**Comment by emanuelschuetze** [comment]
Closed after discussed with @normanjaeckel
