### ISSUE TITLE
Broken login with anonymous

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3377]
```2017-08-25 10:13:29,753 - ERROR - worker - Error processing message with consumer openslides.utils.autoupdate.ws_add_site:
Traceback (most recent call last):
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/sessions.py", line 192, in inner
    result = func(message, *args, **kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/auth.py", line 73, in inner
    return func(message, *args, **kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/sessions.py", line 70, in inner
    return func(message, *args, **kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/auth.py", line 89, in inner
    return func(message, *args, **kwargs)
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/autoupdate.py", line 93, in ws_add_site
    restricted_data = access_permissions.get_restricted_data(collection, user)
  File "/home/finn/OpenSlides/OpenSlides/openslides/users/access_permissions.py", line 190, in get_restricted_data
    if full['user_id'] == user.id:
AttributeError: 'NoneType' object has no attribute 'id'

```

**Comment by ostcar** [comment]
I have a branch "more_typings" where I add more type informations to functions. With this branch I also found this problem (one function can return None and the return value is used as iterabe). I will fix this issue in this branch in the next days

**Comment by ostcar** [comment]
This error could not be found with our current typing annotations. To find it with mypy, we need type annotations for the entire openslides module, not only for openslides.utils. See: https://github.com/python/mypy/issues/3903
