### ISSUE TITLE
Error in openslides.utils.autoupdate.ws_add_site

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3381]
With current master I get this error in autoupdate.py:

```
2017-08-29 21:06:35,329 - ERROR - worker - Error processing message with consumer openslides.utils.autoupdate.ws_add_site:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/channels/sessions.py", line 220, in inner
    result = func(message, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/channels/auth.py", line 73, in inner
    return func(message, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/channels/sessions.py", line 78, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/channels/auth.py", line 89, in inner
    return func(message, *args, **kwargs)
  File "/app/openslides/utils/autoupdate.py", line 103, in ws_add_site
    id=data['id'],
KeyError: 'id'
```

I cannot login in an instance with a migrated database. Works well with a new database. (big mode setup)

@ostcar : You changed this line in your pull request #3371:
https://github.com/OpenSlides/OpenSlides/blame/master/openslides/utils/autoupdate.py#L103
Can you give me a hint how to fix this? Or can you create a new pull request please? It's critical because I can't update production instances!

**Comment by ostcar** [comment]
Can you please  confirm that this is a problem with the SQL-database and not only with redis?
I think it should help to clear the cache. I did not change anything on the SQL-database

**Comment by emanuelschuetze** [comment]
Seems to be a redis cache problem. Works with cleared cache.
