### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3399]
Since the new caching, but only thrown seldom and randomly (it seems to be; happens 9 times out of 200 while performance testing)
@ostcar 
```
Traceback (most recent call last):
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/sessions.py", line 220, in inner
    result = func(message, *args, **kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/auth.py", line 73, in inner
    return func(message, *args, **kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/sessions.py", line 78, in inner
    return func(*args, **kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/auth.py", line 89, in inner
    return func(message, *args, **kwargs)
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/autoupdate.py", line 95, in ws_add_site                             
    output = restricted_data_cache.get_data(user_id)                                
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/cache.py", line 251, in get_data                                    
    return [json.loads(element) for element in redis.hvals(self.get_cache_key(user_id))]                                      
  File "/home/finn/OpenSlides/OpenSlides/openslides/utils/cache.py", line 251, in <listcomp>                                  
    return [json.loads(element) for element in redis.hvals(self.get_cache_key(user_id))]                                      
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads                    
    s.__class__.__name__))                
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by FinnStutzenstein** [comment]
Temporary changed line 251 in utils/cahce.py to `return [json.loads(element.decode('utf-8')) if isinstance(element, bytes) else json.loads(element) for element in redis.hvals(self.get_cache_key(user_id))]` for testing. This works.

**Comment by ostcar** [comment]
I already fixed this in: https://github.com/OpenSlides/OpenSlides/pull/3390

This bug is only for python 3.4 and python 3.5. So you can update your software to get it fixed right away ;)
