### ISSUE TITLE
Follow recommendation server bug

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3542]
When following a recommendation:

```
Traceback (most recent call last):
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/handler.py", line 243, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
    response = self.handle_exception(exc)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/views.py", line 434, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/finn/OpenSlides/OpenSlides/openslides/motions/views.py", line 407, in follow_recommendation
    if 'forState' in field and field['forState'] is True:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by FinnStutzenstein** [comment]
Closed with #3549
