### ISSUE TITLE
ImportError: cannot import name 'build_endpoint_description_strings'

### ISSUE THREAD

**Issue by mwaeckerlin** [OpenSlides/OpenSlides#3574]
[Build / installation instructions for Linux](https://github.com/OpenSlides/OpenSlides/blob/master/README.rst#installation) are wrong.

Setup (in a Docker build) according to the documentation:
```
FROM mwaeckerlin/ubuntu-base
MAINTAINER mwaeckerlin

RUN apt-get update && apt-get install -y build-essential python3 python3-dev python3-pip python3-venv
#RUN ln $(which pip3) /usr/bin/pip
RUN mkdir /openslides
WORKDIR /openslides
RUN python3 -m venv .virtualenv
RUN . .virtualenv/bin/activate && pip3 install --upgrade setuptools pip && pip install openslides
CMD . .virtualenv/bin/activate && openslides
EXPOSE 8000
```
Result:
```
marc@jupiter:~/docker/openslides$ docker build --pull --rm --force-rm -t mwaeckerlin/openslides .
Sending build context to Docker daemon  3.072kB
Step 1/9 : FROM mwaeckerlin/ubuntu-base
latest: Pulling from mwaeckerlin/ubuntu-base
Digest: sha256:e9207a59d15739dec5d1b55412f15c0661383fad23f8d2914b7b688d193c0871
Status: Image is up to date for mwaeckerlin/ubuntu-base:latest
 ---> 66aa06d7a865
Step 2/9 : MAINTAINER mwaeckerlin
 ---> Using cache
 ---> 62e7ec9e8beb
Step 3/9 : RUN apt-get update && apt-get install -y build-essential python3 python3-dev python3-pip python3-venv
 ---> Using cache
 ---> c06ef14d1d39
Step 4/9 : RUN mkdir /openslides
 ---> Running in 7acc9a0cf93f
Removing intermediate container 7acc9a0cf93f
 ---> 6455c1486460
Step 5/9 : WORKDIR /openslides
Removing intermediate container 0944cd34180c
 ---> fcb5d355f482
Step 6/9 : RUN python3 -m venv .virtualenv
 ---> Running in a07630d930d4
Removing intermediate container a07630d930d4
 ---> 262562fdd3e2
Step 7/9 : RUN . .virtualenv/bin/activate && pip3 install --upgrade setuptools pip && pip install openslides
 ---> Running in 50e79be3ab8c
Collecting setuptools
  Downloading setuptools-38.5.1-py2.py3-none-any.whl (489kB)
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
Installing collected packages: setuptools, pip
  Found existing installation: setuptools 20.7.0
    Uninstalling setuptools-20.7.0:
      Successfully uninstalled setuptools-20.7.0
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
Successfully installed pip-9.0.1 setuptools-38.5.1
Collecting openslides
  Downloading openslides-2.1.1-py3-none-any.whl (3.6MB)
Collecting roman<2.1,>=2.0 (from openslides)
  Downloading roman-2.0.0.zip
Collecting jsonfield<1.1,>=1.0 (from openslides)
  Downloading jsonfield-1.0.3.tar.gz
Collecting Django<1.11,>=1.10.4 (from openslides)
  Downloading Django-1.10.8-py2.py3-none-any.whl (6.8MB)
Collecting PyPDF2<1.27,>=1.26 (from openslides)
  Downloading PyPDF2-1.26.0.tar.gz (77kB)
Collecting setuptools<35.0,>=29.0 (from openslides)
  Downloading setuptools-34.4.1-py2.py3-none-any.whl (390kB)
Collecting djangorestframework<3.5,>=3.4 (from openslides)
  Downloading djangorestframework-3.4.7-py2.py3-none-any.whl (706kB)
Collecting channels<1.1,>=1.0 (from openslides)
  Downloading channels-1.0.3-py2.py3-none-any.whl (65kB)
Collecting bleach<1.6,>=1.5.0 (from openslides)
  Downloading bleach-1.5.0-py2.py3-none-any.whl
Collecting appdirs>=1.4.0 (from setuptools<35.0,>=29.0->openslides)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Collecting packaging>=16.8 (from setuptools<35.0,>=29.0->openslides)
  Downloading packaging-16.8-py2.py3-none-any.whl
Collecting six>=1.6.0 (from setuptools<35.0,>=29.0->openslides)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting asgiref>=1.0.0 (from channels<1.1,>=1.0->openslides)
  Downloading asgiref-2.1.4-py2.py3-none-any.whl
Collecting daphne>=1.0.0 (from channels<1.1,>=1.0->openslides)
  Downloading daphne-2.0.3-py2.py3-none-any.whl
Collecting html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999 (from bleach<1.6,>=1.5.0->openslides)
  Downloading html5lib-0.9999999.tar.gz (889kB)
Collecting pyparsing (from packaging>=16.8->setuptools<35.0,>=29.0->openslides)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
Collecting async-timeout~=2.0 (from asgiref>=1.0.0->channels<1.1,>=1.0->openslides)
  Downloading async_timeout-2.0.0-py3-none-any.whl
Collecting twisted>=17.5 (from daphne>=1.0.0->channels<1.1,>=1.0->openslides)
  Downloading Twisted-17.9.0.tar.bz2 (3.0MB)
Collecting autobahn>=0.18 (from daphne>=1.0.0->channels<1.1,>=1.0->openslides)
  Downloading autobahn-17.10.1-py2.py3-none-any.whl (283kB)
Collecting zope.interface>=4.0.2 (from twisted>=17.5->daphne>=1.0.0->channels<1.1,>=1.0->openslides)
  Downloading zope.interface-4.4.3-cp35-cp35m-manylinux1_x86_64.whl (173kB)
Collecting constantly>=15.1 (from twisted>=17.5->daphne>=1.0.0->channels<1.1,>=1.0->openslides)
  Downloading constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from twisted>=17.5->daphne>=1.0.0->channels<1.1,>=1.0->openslides)
  Downloading incremental-17.5.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0 (from twisted>=17.5->daphne>=1.0.0->channels<1.1,>=1.0->openslides)
  Downloading Automat-0.6.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1 (from twisted>=17.5->daphne>=1.0.0->channels<1.1,>=1.0->openslides)
  Downloading hyperlink-17.3.1-py2.py3-none-any.whl (73kB)
Collecting txaio>=2.7.0 (from autobahn>=0.18->daphne>=1.0.0->channels<1.1,>=1.0->openslides)
  Downloading txaio-2.8.2-py2.py3-none-any.whl
Collecting attrs (from Automat>=0.3.0->twisted>=17.5->daphne>=1.0.0->channels<1.1,>=1.0->openslides)
  Downloading attrs-17.4.0-py2.py3-none-any.whl
Installing collected packages: roman, Django, jsonfield, PyPDF2, appdirs, pyparsing, six, packaging, setuptools, djangorestframework, async-timeout, asgiref, zope.interface, constantly, incremental, attrs, Automat, hyperlink, twisted, txaio, autobahn, daphne, channels, html5lib, bleach, openslides
  Running setup.py install for roman: started
    Running setup.py install for roman: finished with status 'done'
  Running setup.py install for jsonfield: started
    Running setup.py install for jsonfield: finished with status 'done'
  Running setup.py install for PyPDF2: started
    Running setup.py install for PyPDF2: finished with status 'done'
  Found existing installation: setuptools 38.5.1
    Uninstalling setuptools-38.5.1:
      Successfully uninstalled setuptools-38.5.1
  Running setup.py install for twisted: started
    Running setup.py install for twisted: finished with status 'done'
  Running setup.py install for html5lib: started
    Running setup.py install for html5lib: finished with status 'done'
Successfully installed Automat-0.6.0 Django-1.10.8 PyPDF2-1.26.0 appdirs-1.4.3 asgiref-2.1.4 async-timeout-2.0.0 attrs-17.4.0 autobahn-17.10.1 bleach-1.5.0 channels-1.0.3 constantly-15.1.0 daphne-2.0.3 djangorestframework-3.4.7 html5lib-0.9999999 hyperlink-17.3.1 incremental-17.5.0 jsonfield-1.0.3 openslides-2.1.1 packaging-16.8 pyparsing-2.2.0 roman-2.0.0 setuptools-34.4.1 six-1.11.0 twisted-17.9.0 txaio-2.8.2 zope.interface-4.4.3
Removing intermediate container 50e79be3ab8c
 ---> e27a1113608c
Step 8/9 : CMD . .virtualenv/bin/activate && openslides
 ---> Running in 37ad061b71f9
Removing intermediate container 37ad061b71f9
 ---> f3d8fe726ede
Step 9/9 : EXPOSE 8000
 ---> Running in bceb88e5d81a
Removing intermediate container bceb88e5d81a
 ---> dafd6a3315ae
Successfully built dafd6a3315ae
Successfully tagged mwaeckerlin/openslides:latest
marc@jupiter:~/docker/openslides$ docker run -it --rm --name slides -p 8000:8000 mwaeckerlin/openslides
Settings created at /root/.config/openslides/settings.py
Traceback (most recent call last):
  File "/openslides/.virtualenv/bin/openslides", line 11, in <module>
    sys.exit(main())
  File "/openslides/.virtualenv/lib/python3.5/site-packages/openslides/__main__.py", line 47, in main
    known_args.callback(known_args)
  File "/openslides/.virtualenv/lib/python3.5/site-packages/openslides/__main__.py", line 187, in start
    django.setup()
  File "/openslides/.virtualenv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/openslides/.virtualenv/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/openslides/.virtualenv/lib/python3.5/site-packages/channels/apps.py", line 22, in ready
    monkeypatch_django()
  File "/openslides/.virtualenv/lib/python3.5/site-packages/channels/hacks.py", line 10, in monkeypatch_django
    from .management.commands.runserver import Command as RunserverCommand
  File "/openslides/.virtualenv/lib/python3.5/site-packages/channels/management/commands/runserver.py", line 5, in <module>
    from daphne.server import Server, build_endpoint_description_strings
ImportError: cannot import name 'build_endpoint_description_strings'
marc@jupiter:~/docker/openslides$
```

**Comment by FinnStutzenstein** [comment]
Hi, I had the same issue here: https://github.com/OpenSlides/openslides-protocol/issues/11
You may lock down daphne to use version 1.x instead of the new released 2.x. Interestingly, if I install requirements, daphne is not updated. I'll check this next week.

**Comment by mwaeckerlin** [comment]
@FinnStutzenstein 
> As a hotfix make an explicit call for 'pip install daphne<2'. Does this fix your problem?

Yes, it fixes the problem.

No I use the following Docker build script:
```
FROM mwaeckerlin/ubuntu-base
MAINTAINER mwaeckerlin

#RUN apt-get update && apt-get install -y build-essential python3 python3-dev python3-pip python3-venv
##RUN ln $(which pip3) /usr/bin/pip
#RUN mkdir /openslides
#WORKDIR /openslides
#RUN python3 -m venv .virtualenv
#RUN . .virtualenv/bin/activate && pip3 install --upgrade setuptools pip && pip install openslides
#CMD . .virtualenv/bin/activate && openslides

RUN apt-get update && apt-get install -y python3 python3-setuptools python3-dev gcc
ENV VERSION "2.1.1"
ENV SOURCE "https://files.openslides.org/releases/${VERSION}/openslides-${VERSION}.tar.gz"
RUN wget -qOopenslides-${VERSION}.tar.gz $SOURCE
RUN tar xf openslides-${VERSION}.tar.gz
WORKDIR openslides-${VERSION}
RUN python3 setup.py install

# bugfix for https://github.com/OpenSlides/OpenSlides/issues/3574#issuecomment-364559454
RUN apt-get install -y python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install 'daphne<2'

CMD openslides

EXPOSE 8000
```

Other question: Where are the data, what do I need to specify as persistent volume to not loose all my configurations?

**Comment by jsaalfeld** [comment]
> As a hotfix make an explicit call for 'pip install daphne<2'. Does this fix your problem?
This was added in #3579 
An update for channel 2.x, Django 2.x and therefore daphne 2.x will be planned in #3582
