### ISSUE TITLE
latest beta 3 preview cannot open existing databases

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3675]
I just got a new build from today from Emanuel. With this I cannot open any database I created with 2.2 beta 1 or beta 2.
I get these errors:

Operations to perform:
  Apply all migrations: agenda, assignments, auth, contenttypes, core, mediafiles, motions, sessions, topics, users
Running migrations:
  No migrations to apply.
The following content types are stale and need to be deleted:

    users | personalnote

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: Traceback (most recent call last):
  File "D:\OpenSlides\2.2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\OpenSlides\2.2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\OpenSlides\2.2\lib\site-packages\openslides\__main__.py", line 265, in <module>
    sys.exit(main())
  File "D:\OpenSlides\2.2\lib\site-packages\openslides\__main__.py", line 47, in main
    known_args.callback(known_args)
  File "D:\OpenSlides\2.2\lib\site-packages\openslides\__main__.py", line 191, in start
    call_command('migrate')
  File "D:\OpenSlides\2.2\lib\site-packages\django\core\management\__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "D:\OpenSlides\2.2\lib\site-packages\django\core\management\base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "D:\OpenSlides\2.2\lib\site-packages\openslides\core\management\commands\migrate.py", line 23, in handle
    super().handle(*args, **options)
  File "D:\OpenSlides\2.2\lib\site-packages\django\core\management\commands\migrate.py", line 224, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "D:\OpenSlides\2.2\lib\site-packages\django\core\management\sql.py", line 53, in emit_post_migrate_signal
    **kwargs
  File "D:\OpenSlides\2.2\lib\site-packages\django\dispatch\dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "D:\OpenSlides\2.2\lib\site-packages\django\contrib\contenttypes\management.py", line 158, in update_contenttypes
    Type 'yes' to continue, or 'no' to cancel: """ % content_type_display)
EOFError: EOF when reading a line

**Comment by emanuelschuetze** [comment]
Cannot reproduce it.

**Comment by donovaly** [comment]
Confirmed fixed in beta 3.
