### ISSUE TITLE
IndexError: list index out of range on WebSockets handshake

### ISSUE THREAD

**Issue by serge1peshcoff** [OpenSlides/OpenSlides#3710]
I'm getting error when trying to log in for some users:

    2018-04-15 12:51:34,667 - ERROR - worker - Error processing message with consumer openslides.utils.autoupdate.ws_add_site:
    Traceback (most recent call last):
    File "/home/chair/.pyenv/versions/3.6.5/lib/python3.6/site-packages/channels/worker.py", line 119, in run
        consumer(message, **kwargs)
    File "/home/chair/.pyenv/versions/3.6.5/lib/python3.6/site-packages/channels/sessions.py", line 220, in inner
        result = func(message, *args, **kwargs)
    File "/home/chair/.pyenv/versions/3.6.5/lib/python3.6/site-packages/channels/auth.py", line 73, in inner
        return func(message, *args, **kwargs)
    File "/home/chair/.pyenv/versions/3.6.5/lib/python3.6/site-packages/channels/sessions.py", line 78, in inner
        return func(*args, **kwargs)
    File "/home/chair/.pyenv/versions/3.6.5/lib/python3.6/site-packages/channels/auth.py", line 89, in inner
        return func(message, *args, **kwargs)
    File "/home/chair/Agora/Krakow/OpenSlides/openslides/utils/autoupdate.py", line 87, in ws_add_site
        restricted_data = access_permissions.get_restricted_data(collection.get_full_data(), user)
    File "/home/chair/Agora/Krakow/OpenSlides/openslides/agenda/access_permissions.py", line 60, in get_restricted_data
        blocked_keys_hidden_case = set(full_data[0].keys()) - set((
    IndexError: list index out of range

Not sure what can cause it, but I can provide additional details.
OpenSlides 2.2b4-dev, Python 3.6.5, run in Debian 8 x64.

**Comment by serge1peshcoff** [comment]
Actually no, not on login but apparently on connecting websockets, here is the full log:

```
chair@agora:~/Agora/Krakow/OpenSlides$ python3 manage.py start --local-installation --no-browser
Operations to perform:
  Apply all migrations: agenda, assignments, auth, contenttypes, core, mediafiles, motions, sessions, topics, users
Running migrations:
  No migrations to apply.
Performing system checks...

System check identified no issues (0 silenced).
April 15, 2018 - 12:55:45
Django version 1.10.8, using settings 'settings'
Starting Channels development server at http://0.0.0.0:8000/
Channel layer default (asgiref.inmemory.ChannelLayer)
Quit the server with CONTROL-C.
2018-04-15 12:55:45,669 - INFO - worker - Listening on channels autoupdate.send_data_projector, autoupdate.send_data_site, http.request, websocket.connect, websocket.disconnect, websocket.receive
2018-04-15 12:55:45,669 - INFO - server - HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2018-04-15 12:55:45,670 - INFO - server - Using busy-loop synchronous mode on channel layer
2018-04-15 12:55:45,670 - INFO - server - Listening on endpoint tcp:port=8000:interface=0.0.0.0
[2018/04/15 12:55:46] HTTP GET /users/whoami 301 [0.05, 217.25.236.134:63336]
[2018/04/15 12:55:46] HTTP GET /users/whoami/ 200 [0.10, 217.25.236.134:63336]
[2018/04/15 12:55:46] WebSocket HANDSHAKING /ws/site/ [217.25.236.134:63337]
[2018/04/15 12:55:46] WebSocket CONNECT /ws/site/ [217.25.236.134:63337]
2018-04-15 12:55:48,739 - ERROR - worker - Error processing message with consumer openslides.utils.autoupdate.ws_add_site:
Traceback (most recent call last):
  File "/home/chair/.pyenv/versions/3.6.5/lib/python3.6/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/home/chair/.pyenv/versions/3.6.5/lib/python3.6/site-packages/channels/sessions.py", line 220, in inner
    result = func(message, *args, **kwargs)
  File "/home/chair/.pyenv/versions/3.6.5/lib/python3.6/site-packages/channels/auth.py", line 73, in inner
    return func(message, *args, **kwargs)
  File "/home/chair/.pyenv/versions/3.6.5/lib/python3.6/site-packages/channels/sessions.py", line 78, in inner
    return func(*args, **kwargs)
  File "/home/chair/.pyenv/versions/3.6.5/lib/python3.6/site-packages/channels/auth.py", line 89, in inner
    return func(message, *args, **kwargs)
  File "/home/chair/Agora/Krakow/OpenSlides/openslides/utils/autoupdate.py", line 87, in ws_add_site
    restricted_data = access_permissions.get_restricted_data(collection.get_full_data(), user)
  File "/home/chair/Agora/Krakow/OpenSlides/openslides/agenda/access_permissions.py", line 60, in get_restricted_data
    blocked_keys_hidden_case = set(full_data[0].keys()) - set((
IndexError: list index out of range
[2018/04/15 12:55:48] HTTP GET /users/whoami/ 200 [1.81, 217.25.236.134:63336]
[2018/04/15 12:55:48] WebSocket HANDSHAKING /ws/site/ [217.25.236.134:63340]
[2018/04/15 12:55:48] HTTP GET /users/whoami/ 200 [0.78, 217.25.236.134:63338]
[2018/04/15 12:55:49] WebSocket CONNECT /ws/site/ [217.25.236.134:63340]
[2018/04/15 12:55:49] WebSocket HANDSHAKING /ws/site/ [217.25.236.134:63341]
2018-04-15 12:55:50,946 - ERROR - worker - Error processing message with consumer openslides.utils.autoupdate.ws_add_site:
Traceback (most recent call last):
  File "/home/chair/.pyenv/versions/3.6.5/lib/python3.6/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/home/chair/.pyenv/versions/3.6.5/lib/python3.6/site-packages/channels/sessions.py", line 220, in inner
    result = func(message, *args, **kwargs)
  File "/home/chair/.pyenv/versions/3.6.5/lib/python3.6/site-packages/channels/auth.py", line 73, in inner
    return func(message, *args, **kwargs)
  File "/home/chair/.pyenv/versions/3.6.5/lib/python3.6/site-packages/channels/sessions.py", line 78, in inner
    return func(*args, **kwargs)
  File "/home/chair/.pyenv/versions/3.6.5/lib/python3.6/site-packages/channels/auth.py", line 89, in inner
    return func(message, *args, **kwargs)
  File "/home/chair/Agora/Krakow/OpenSlides/openslides/utils/autoupdate.py", line 87, in ws_add_site
    restricted_data = access_permissions.get_restricted_data(collection.get_full_data(), user)
  File "/home/chair/Agora/Krakow/OpenSlides/openslides/agenda/access_permissions.py", line 60, in get_restricted_data
    blocked_keys_hidden_case = set(full_data[0].keys()) - set((
IndexError: list index out of range
```

**Comment by FinnStutzenstein** [comment]
Hi, it semms, that some agenda item is corrupt. Can you share some of your database content? If so, please try to open "your-instance/rest" and click on agenda/item. I have the feeling, that this might fail. If so but you dont get a detailed error, please set 'DEBUG=True' in your settings.py.

**Comment by serge1peshcoff** [comment]
I've removed the `personal_data/` folder, recreated the settings and everything is OK now. Should've been something with my configuration indeed.
But still, can OpenSlides display some more info about what is corrupted and what to do (how to reset the settings/find out what is wrong)? That would be more useful, (although it will happen rarely, I suppose, but still when something is corrupted, you would like to know what).

**Comment by serge1peshcoff** [comment]
@FinnStutzenstein forgot to mention you there, what do you think about what I've described in the comment above?

**Comment by FinnStutzenstein** [comment]
First, did you also delete your database? I would say, that this error does not come from the settings. So now we cannot recreate this to fix it.

For the error handling: Those errors are too wide spread to always give detailed instructions how to fix them. Especially errors like this, which shall not occur (btw. I cannot get why this was failing, so there isn't a possibility to give instructions on things we do not know to happen).
We may create a troubleshooting guide where a user can look up some basics steps so he can give more detailed information in an issue. But this has to be created...
