### ISSUE TITLE
User cannot edit user profile

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3898]
Tested with OpenSlides 2.3:
* Create a new user with delegate group
* Login as this user
* Try to edit user profil (e.g. email address or about-me field)
=> Server error ("AttributeError: 'dict' object has no attribute '_mutable'")

```
Internal Server Error: /rest/users/user/5/
Traceback (most recent call last):
  File "/home/emanuel/openslides/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/emanuel/openslides/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/emanuel/openslides/.venv/lib/python3.7/site-packages/channels/handler.py", line 243, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/home/emanuel/openslides/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/emanuel/openslides/.venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/emanuel/openslides/.venv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/emanuel/openslides/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 474, in dispatch
    response = self.handle_exception(exc)
  File "/home/emanuel/openslides/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 434, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/emanuel/openslides/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/emanuel/openslides/openslides/users/views.py", line 98, in update
    request.data._mutable = True
AttributeError: 'dict' object has no attribute '_mutable'
[2018/09/27 15:20:37] HTTP PUT /rest/users/user/5/ 500 [0.15, 127.0.0.1:57924]
```

As admin with all user permissions ('Can see names of users', 'Can see extra data of users', 'Can manage users') it works without errors. But if you remove the 'can manage' permission you get the same error.

Any idea?

**Comment by normanjaeckel** [comment]
@ostcar Any idea? The "mutable" thing comes from you I think. If one is manager the problem does not appear because we to not manipulate the request data so we do not have the hack to to make request.data mutable.

**Comment by ostcar** [comment]
This is a hack to support the current version of django. The right solution would be, not to change the request data. But this is probably not possible on our current code basis.

To solve this, you first have to check, if request.data is a dict or a querydict. Only if it is a querydict, you can (and have to) set _mutable = true.

See https://github.com/OpenSlides/OpenSlides/blob/d4f9da9cdb59b94a69e6a87d32e79a993db33b39/openslides/motions/views.py#L110:L112

So the fix is to change this line: https://github.com/OpenSlides/OpenSlides/blob/d4f9da9cdb59b94a69e6a87d32e79a993db33b39/openslides/users/views.py#L98 to 

```python
        if isinstance(request.data, QueryDict):
            request.data._mutable = True
```

**Comment by ostcar** [comment]
I think this bug is solved. It not reopen
