### ISSUE TITLE
Can't apply migrations on PostgreSQL

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#3987]
While trying to update the Docker-Environment for version 3, I stumbled upon the problem, that I can't apply the migrations to a fresh postres-instance:

```
postgres_1_b93c2e922be2 | Creating replication user: repluser
postgres_1_b93c2e922be2 | Starting PostgreSQL 9.6...
postgres_1_b93c2e922be2 | LOG:  database system was shut down at 2018-11-06 10:54:57 UTC
postgres_1_b93c2e922be2 | LOG:  MultiXact member wraparound protections are now enabled
postgres_1_b93c2e922be2 | LOG:  autovacuum launcher started
postgres_1_b93c2e922be2 | LOG:  database system is ready to accept connections
postgres_1_b93c2e922be2 | ERROR:  relation "motions_workflow" does not exist at character 101
postgres_1_b93c2e922be2 | STATEMENT:  SELECT "motions_workflow"."id", "motions_workflow"."name", "motions_workflow"."first_state_id" FROM "motions_workflow"
server_1_4d493c88160b | Traceback (most recent call last):
server_1_4d493c88160b |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
server_1_4d493c88160b |     return self.cursor.execute(sql, params)
server_1_4d493c88160b | psycopg2.ProgrammingError: relation "motions_workflow" does not exist
server_1_4d493c88160b | LINE 1: ...."name", "motions_workflow"."first_state_id" FROM "motions_w...
server_1_4d493c88160b |                                                              ^
server_1_4d493c88160b | 
server_1_4d493c88160b | 
server_1_4d493c88160b | The above exception was the direct cause of the following exception:
server_1_4d493c88160b | 
server_1_4d493c88160b | Traceback (most recent call last):
server_1_4d493c88160b |   File "manage.py", line 11, in <module>
server_1_4d493c88160b |     exit(main())
server_1_4d493c88160b |   File "/app/openslides/__main__.py", line 41, in main
server_1_4d493c88160b |     execute_from_command_line(sys.argv)
server_1_4d493c88160b |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
server_1_4d493c88160b |     utility.execute()
server_1_4d493c88160b |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
server_1_4d493c88160b |     django.setup()
server_1_4d493c88160b |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
server_1_4d493c88160b |     apps.populate(settings.INSTALLED_APPS)
server_1_4d493c88160b |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 120, in populate
server_1_4d493c88160b |     app_config.ready()
server_1_4d493c88160b |   File "/app/openslides/core/apps.py", line 55, in ready
server_1_4d493c88160b |     set_constants(get_constants_from_apps())
server_1_4d493c88160b |   File "/app/openslides/utils/constants.py", line 16, in get_constants_from_apps
server_1_4d493c88160b |     out.update(get_angular_constants())
server_1_4d493c88160b |   File "/app/openslides/core/apps.py", line 147, in get_angular_constants
server_1_4d493c88160b |     config_groups[-1]['subgroups'][-1]['items'].append(config_variable.data)
server_1_4d493c88160b |   File "/app/openslides/core/config.py", line 305, in data
server_1_4d493c88160b |     choices=self.choices() if callable(self.choices) else self.choices
server_1_4d493c88160b |   File "/app/openslides/motions/config_variables.py", line 14, in get_workflow_choices
server_1_4d493c88160b |     for workflow in Workflow.objects.all()]
server_1_4d493c88160b |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 268, in __iter__
server_1_4d493c88160b |     self._fetch_all()
server_1_4d493c88160b |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _fetch_all
server_1_4d493c88160b |     self._result_cache = list(self._iterable_class(self))
server_1_4d493c88160b |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 54, in __iter__
server_1_4d493c88160b |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
server_1_4d493c88160b |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
server_1_4d493c88160b |     cursor.execute(sql, params)
server_1_4d493c88160b |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
server_1_4d493c88160b |     return super().execute(sql, params)
server_1_4d493c88160b |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
server_1_4d493c88160b |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
server_1_4d493c88160b |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
server_1_4d493c88160b |     return executor(sql, params, many, context)
server_1_4d493c88160b |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
server_1_4d493c88160b |     return self.cursor.execute(sql, params)
server_1_4d493c88160b |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
server_1_4d493c88160b |     raise dj_exc_value.with_traceback(traceback) from exc_value
server_1_4d493c88160b |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
server_1_4d493c88160b |     return self.cursor.execute(sql, params)
server_1_4d493c88160b | django.db.utils.ProgrammingError: relation "motions_workflow" does not exist
server_1_4d493c88160b | LINE 1: ...."name", "motions_workflow"."first_state_id" FROM "motions_w...
```

It can be reproduced with a local setup, so it isn't a docker-issue.

**Comment by jsaalfeld** [comment]
You can recreate the issue by starting up a postres instance. e.g via:

    docker run --name os-postgres -p 5432:5432 -e POSTGRES_PASSWORD=openslides -e POSTGRES_USER=openslides postgres

and change the db-part in the settings to:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'openslides',
        'USER': 'openslides',
        'PASSWORD': 'openslides',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}
```

The log from postgres will tell you:
PostgreSQL init process complete; ready for start up.
```
2018-11-06 11:18:12.430 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2018-11-06 11:18:12.430 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2018-11-06 11:18:12.436 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2018-11-06 11:18:12.471 UTC [62] LOG:  database system was shut down at 2018-11-06 11:18:12 UTC
2018-11-06 11:18:12.478 UTC [1] LOG:  database system is ready to accept connections
2018-11-06 11:18:18.851 UTC [69] ERROR:  relation "motions_workflow" does not exist at character 101
2018-11-06 11:18:18.851 UTC [69] STATEMENT:  SELECT "motions_workflow"."id", "motions_workflow"."name", "motions_workflow"."first_state_id" FROM "motions_workflow"
```

The `python manage.py migrate` will tell you:

```
% python manage.py migrate              
Traceback (most recent call last):
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "motions_workflow" does not exist
LINE 1: ...."name", "motions_workflow"."first_state_id" FROM "motions_w...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    exit(main())
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/openslides/__main__.py", line 41, in main
    execute_from_command_line(sys.argv)
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/openslides/core/apps.py", line 55, in ready
    set_constants(get_constants_from_apps())
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/openslides/utils/constants.py", line 16, in get_constants_from_apps
    out.update(get_angular_constants())
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/openslides/core/apps.py", line 147, in get_angular_constants
    config_groups[-1]['subgroups'][-1]['items'].append(config_variable.data)
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/openslides/core/config.py", line 305, in data
    choices=self.choices() if callable(self.choices) else self.choices
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/openslides/motions/config_variables.py", line 14, in get_workflow_choices
    for workflow in Workflow.objects.all()]
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/db/models/query.py", line 268, in __iter__
    self._fetch_all()
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "motions_workflow" does not exist
LINE 1: ...."name", "motions_workflow"."first_state_id" FROM "motions_w...
                                                             ^

```

**Comment by jsaalfeld** [comment]
Since #3988 is merged. This is fixed now.
