### ISSUE TITLE
create-example-data failed with KeyError: 'core/config'

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#4066]
- Enable the built-in plugin 'tests.example_data_generator' in settings.py 
- run `python manage.py create-example-data` on current master

```
Start creating 100 topcis ...
100 topcis successfully created.
Start creating 100 motions ...
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    exit(main())
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/__main__.py", line 41, in main
    execute_from_command_line(sys.argv)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/emanuel/projects/openslides/src/OpenSlides/tests/example_data_generator/management/commands/create-example-data.py", line 116, in handle
    self.create_motions(options)
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/emanuel/projects/openslides/src/OpenSlides/tests/example_data_generator/management/commands/create-example-data.py", line 155, in create_motions
    motion.save(skip_autoupdate=True)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/motions/models.py", line 275, in save
    self.reset_state()
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/motions/models.py", line 467, in reset_state
    new_state = (Workflow.objects.get(pk=config['motions_workflow']).first_state or
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/core/config.py", line 59, in __getitem__
    return async_to_sync(element_cache.get_element_full_data)(self.get_collection_string(), self.get_key_to_id()[key])['value']
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/core/config.py", line 66, in get_key_to_id
    async_to_sync(self.build_key_to_id)()
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/asgiref/sync.py", line 64, in __call__
    return call_result.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/asgiref/sync.py", line 78, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/core/config.py", line 81, in build_key_to_id
    elements = all_data[self.get_collection_string()]
KeyError: 'core/config'
```

@normanjaeckel Can you fix this please? Thanks.

**Comment by emanuelschuetze** [comment]
@normanjaeckel or maybe @ostcar Can you look at this error please next days? We need this example data script for testing with huge datasets.
