### ISSUE TITLE
Serializer Error on startup

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#4069]
With the commit of #3985 the openslides server-start routine was broken.

When you try to startup the server, the following error will greet you:

```
% python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f2d793c79d8>
Traceback (most recent call last):
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/.virtualenv/lib/python3.7/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/openslides/core/apps.py", line 90, in ready
    element_cache.ensure_cache()
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/openslides/utils/cache.py", line 102, in ensure_cache
    for element in cachable.get_elements():
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/openslides/utils/models.py", line 122, in get_elements
    return [instance.get_full_data() for instance in query.all()]
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/openslides/utils/models.py", line 122, in <listcomp>
    return [instance.get_full_data() for instance in query.all()]
  File "/home/jochen/VCS/GIT/jsaalfeld/OpenSlides/openslides/utils/models.py", line 138, in get_full_data
    serializer_class = model_serializer_classes[type(self)]
KeyError: <class 'openslides.users.models.User'>
```

When you change back your commit to a commit before #3985 it still works.

We need do discuss quickly if we revert or try to fix the bug **asap**.

Additionally, we should discuss some code reviewing guidelines for the server and add maybe another server-check to travis, to prevent something like this from happening.

**Comment by emanuelschuetze** [comment]
@ostcar Please look at this issue asap! Can you make a fix the next days? Otherwise we have to revert your PR #3985 until you find a solution for this issue.

**Comment by ostcar** [comment]
See #4073

**Comment by normanjaeckel** [comment]
See my comment at #4073. I have some questions to the current solution.

**Comment by jsaalfeld** [comment]
A new issue rose in this area.

You try to import the module now, when you don't find the key in the ([openslides/utils/models.py#L148](https://github.com/OpenSlides/OpenSlides/blob/ebf51507f8eb58886c2f42707ffd691b3062d63b/openslides/utils/models.py#L148)). This leads to a potential `ModuleNotFoundError` in which I just ran, as I tested if the pypi-Package from #4095:

```% openslides
Traceback (most recent call last):
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/bin/openslides", line 11, in <module>
    load_entry_point('openslides==3.0.dev0', 'console_scripts', 'openslides')()
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/openslides/__main__.py", line 52, in main
    known_args.callback(known_args)
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/openslides/__main__.py", line 199, in start
    "The start command does not work anymore. "
openslides.utils.exceptions.OpenSlidesError: The start command does not work anymore. Please use `createsettings`, `migrate` and `runserver`.
% openslides createsettings
Settings created at /home/jochen/.config/openslides/settings.py
% openslides migrate       
Operations to perform:
  Apply all migrations: agenda, assignments, auth, contenttypes, core, mediafiles, motions, sessions, topics, users
Running migrations:
  Applying agenda.0003_auto_20170818_1202... OK
  Applying agenda.0004_speaker_marked... OK
  Applying agenda.0005_auto_20180815_1109... OK
  Applying assignments.0004_auto_20180703_1523... OK
  Applying assignments.0005_auto_20180822_1042... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying core.0005_auto_20170412_1258... OK
  Applying core.0006_auto_20180123_0903... OK
  Applying core.0007_auto_20180130_1400... OK
  Applying core.0008_changed_logo_fields... OK
  Applying core.0009_auto_20181118_2126... OK
  Applying users.0004_personalnote... OK
  Applying users.0005_personalnote_rework... OK
  Applying users.0006_user_email... OK
  Applying motions.0003_motion_comments... OK
  Applying motions.0004_motionchangerecommendation_other_description... OK
  Applying motions.0005_auto_20180202_1318... OK
  Applying motions.0006_submitter_model...Traceback (most recent call last):
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/openslides/utils/models.py", line 147, in get_full_data
    serializer_class = model_serializer_classes[type(self)]
KeyError: <class '__fake__.Submitter'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/bin/openslides", line 11, in <module>
    load_entry_point('openslides==3.0.dev0', 'console_scripts', 'openslides')()
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/openslides/__main__.py", line 41, in main
    execute_from_command_line(sys.argv)
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/openslides/core/management/commands/migrate.py", line 25, in handle
    super().handle(*args, **options)
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/openslides/motions/migrations/0006_submitter_model.py", line 27, in move_submitters_to_own_model
    submitter.save(force_insert=True)
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/openslides/utils/models.py", line 92, in save
    inform_changed_data(self.get_root_rest_element())
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/openslides/utils/autoupdate.py", line 67, in inform_changed_data
    full_data=root_instance.get_full_data(),
  File "/home/jochen/VCS/GIT/OpenSlides/openslides-docker/build-pypi/build/.virtualenv/lib/python3.7/site-packages/openslides/utils/models.py", line 153, in get_full_data
    __import__(module_name)
ModuleNotFoundError: No module named '__fake__'
```
