### ISSUE TITLE
ubuntu 18.04 not working

### ISSUE THREAD

**Issue by LeeJZh** [OpenSlides/OpenSlides#4082]
`
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Operations to perform:
  Apply all migrations: agenda, assignments, auth, contenttypes, core, mediafiles, motions, sessions, topics, users
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: main.motions_state__old

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lijzh/anaconda3/bin/openslides", line 11, in <module>
    sys.exit(main())
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/openslides/__main__.py", line 53, in main
    known_args.callback(known_args)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/openslides/__main__.py", line 221, in start
    call_command('migrate')
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/openslides/core/management/commands/migrate.py", line 23, in handle
    super().handle(*args, **options)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 226, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/core/management/sql.py", line 51, in emit_post_migrate_signal
    **kwargs
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/openslides/motions/signals.py", line 21, in create_builtin_workflows
    workflow_1 = Workflow.objects.create(name='Simple Workflow')
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/models/query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/openslides/motions/models.py", line 1390, in save
    super(Workflow, self).save(**kwargs)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/openslides/utils/models.py", line 86, in save
    return_value = super().save(*args, **kwargs)  # type: ignore
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/lijzh/anaconda3/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: main.motions_state__old

`

**Comment by emanuelschuetze** [comment]
Works with django 2.1.5, see #4063.
