### ISSUE TITLE
KeyErrors in motions/projector.py

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#4190]
I run into two KeyErrors in motions/projector.py:

1. Try to create a change recommendation:
```
Internal Server Error: /rest/motions/motion-change-recommendation/
Traceback (most recent call last):
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/autoupdate.py", line 180, in __call__
    handle_changed_elements(bundle.values())
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/autoupdate.py", line 251, in handle_changed_elements
    itertools.chain(elements, history_elements)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/asgiref/sync.py", line 64, in __call__
    return call_result.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/asgiref/sync.py", line 78, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/autoupdate.py", line 217, in async_handle_collection_elements
    projector_data = await get_projector_data()
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/projector.py", line 80, in get_projector_data
    {"data": projector_element(element, all_data), "element": element}
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/motions/projector.py", line 88, in motion_slide
    ][motion["recommendation_id"]]["text"]
KeyError: 3
```

2. Try to project a new motion (with recommendation):

```
Internal Server Error: /rest/core/projector/1/project/
Traceback (most recent call last):
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/autoupdate.py", line 180, in __call__
    handle_changed_elements(bundle.values())
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/autoupdate.py", line 251, in handle_changed_elements
    itertools.chain(elements, history_elements)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/asgiref/sync.py", line 64, in __call__
    return call_result.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/asgiref/sync.py", line 78, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/autoupdate.py", line 217, in async_handle_collection_elements
    projector_data = await get_projector_data()
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/projector.py", line 80, in get_projector_data
    {"data": projector_element(element, all_data), "element": element}
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/motions/projector.py", line 87, in motion_slide
    "motions/motion-change-recommendation"
KeyError: 'motions/motion-change-recommendation'
```
Tested with #4187 
@ostcar Can you fix it please?

**Comment by ostcar** [comment]
I don't konw the motion app anymore. Can you tell me how to create a change_recommendation?

Even better: Could you create an example motion with a change_recommendation and send me the full_data of the example by opening /rest/ end send me the json from all models, that are needed for your example.

**Comment by emanuelschuetze** [comment]
Here my created test motion in `motions/motion`:

```
{
        "id": 4,
        "identifier": "4",
        "title": "Test motion",
        "text": "<p>text</p>",
        "amendment_paragraphs": null,
        "modified_final_version": "",
        "reason": "",
        "parent_id": null,
        "category_id": null,
        "comments": [],
        "motion_block_id": null,
        "origin": "",
        "submitters": [
            {
                "id": 6,
                "user_id": 2,
                "motion_id": 4,
                "weight": 1
            }
        ],
        "supporters_id": [],
        "state_id": 1,
        "state_extension": null,
        "state_required_permission_to_see": "",
        "statute_paragraph_id": null,
        "workflow_id": 1,
        "recommendation_id": 2,
        "recommendation_extension": null,
        "tags_id": [],
        "attachments_id": [],
        "polls": [],
        "agenda_item_id": 5,
        "log_messages": [
            {
                "message_list": "['Recommendation set to', ' ', 'Acceptance']",
                "person_id": 1,
                "time": "2019-01-27T11:27:39.939614+01:00",
                "message": "27. Januar 2019 11:27 Recommendation set to Acceptance by Administrator"
            },
            {
                "message_list": "['Motion updated']",
                "person_id": 1,
                "time": "2019-01-27T11:27:35.507799+01:00",
                "message": "27. Januar 2019 11:27 Motion updated by Administrator"
            },
            {
                "message_list": "['Motion created']",
                "person_id": 1,
                "time": "2019-01-27T11:27:02.283914+01:00",
                "message": "27. Januar 2019 11:27 Motion created by Administrator"
            }
        ],
        "sort_parent_id": null,
        "weight": 10000,
        "created": "2019-01-27T11:27:02.230049+01:00",
        "last_modified": "2019-01-27T11:27:39.897295+01:00"
    }
```

and the corresponding change recommendation in `motions/motion-change-recommendation/`

```
    {
        "id": 3,
        "motion_id": 4,
        "rejected": false,
        "internal": false,
        "type": 1,
        "other_description": "",
        "line_from": 1,
        "line_to": 2,
        "text": "<p>text NEW</p>",
        "creation_time": "2019-01-27T11:28:37.141006+01:00"
    }
```

Note: recommendation and change-recommendation are different things! 
* To select a recommendation label add 'name of recommender' in config. Then you have a drop down list in motion detail (below state name).
* To create a change recommendation you have to activate line numbering 'outside' mode. Then you can move the mouse over line number and click at the blue "+" (first+last line).

For motion slide we need the recommendation_label - currently I can get recommendation_id only.

**Comment by ostcar** [comment]
@emanuelschuetze I think we already fixed this. Could you once more test it and close this issue, if it is fixed?
