### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by ApoRes1337** [OpenSlides/OpenSlides#4198]
Guten Tag zusammen, 

aktuell versuche ich die OpenSlides Software in der Version 2.3 unter Debian Stretch mit MySQL bzw MariaDB zum laufen zu bekommen. 

Jedoch bekomme ich bei folgender Konfiguration: 

`
DATABASES = {
    'default': {
         'ENGINE': 'django.db.backends.mysql',
         'NAME': 'meinedatenbank',
         'USER': 'meindatenbankbenutzer',
         'PASSWORD': 'meintollespasswort',
         'HOST': 'localhost',
         'PORT': '3306',
     }
}
`

die folgende Fehlermeldung: 

`
Traceback (most recent call last):
  File "/usr/local/bin/openslides", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/openslides/__main__.py", line 53, in main
    known_args.callback(known_args)
  File "/usr/local/lib/python3.5/dist-packages/openslides/__main__.py", line 221, in start
    call_command('migrate')
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/openslides/core/management/commands/migrate.py", line 23, in handle
    super().handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 233, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/mysql/base.py", line 265, in get_new_connection
    conn.encoders[SafeBytes] = conn.encoders[bytes]
KeyError: <class 'bytes'>
`

hat jemand zufällig eine Idee woran das liegen könnte ? Ich bin nämlich langsam völlig ratlos.

**Comment by tsiegleauq** [comment]
Hi. OpenSlides 2.3 verlangt Python 3.6 oder höher.

Make sure that you have installed Python (>= 3.6) on your system.


Ich würde vorschlagen, Version 2.2 zu testen oder eine aktuellere Version von Python zu installieren.

**Comment by ApoRes1337** [comment]
@tsiegleauq danke für den Hinweis, soweit bin ich erstmal durch gekommen. Auf wenn mir die Abhängigkeiten etwas Probleme gemacht haben. Bin nun bei Python 3.7. 

Nun beginnt er wohl die DB zu migrieren bricht aber wegen einem zum langen Key wohl ab. 
Liegt dies am Secret Key der in der Settings.py ist ? Denn an sich ist die DB von mir noch leer, ich hatte am System noch nichts gemacht. 

`Operations to perform:
  Apply all migrations: agenda, assignments, auth, contenttypes, core, mediafiles, motions, sessions, topics, users
Running migrations:
  Applying users.0001_initial...Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/cursors.py", line 198, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/cursors.py", line 304, in _query
    db.query(q)
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/connections.py", line 217, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/openslides", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/openslides/__main__.py", line 53, in main
    known_args.callback(known_args)
  File "/usr/local/lib/python3.7/dist-packages/openslides/__main__.py", line 221, in start
    call_command('migrate')
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/dist-packages/openslides/core/management/commands/migrate.py", line 23, in handle
    super().handle(*args, **options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/operations/models.py", line 91, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/schema.py", line 312, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/cursors.py", line 198, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/cursors.py", line 304, in _query
    db.query(q)
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/connections.py", line 217, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
`

**Comment by ApoRes1337** [comment]
Ich habe den Fehler selber gefunden, es lag daran das die Datenbank nicht UTF8 konvertiert war. 
Bedanke mich nochmal herzlichst bei der fixen Hilfe dann kann die Arbeit mit dem Tool doch endlich beginnen. :)

**Comment by tsiegleauq** [comment]
Viel Spaß! ;-)

Transcript in english, in case somebody runs into the same issue and is not able to understand this conversation:

> > > Good afternoon, everyone,
> > >
> > >Currently I'm trying to run the OpenSlides software version 2.3 under Debian Stretch with MySQL or MariaDB.
> > >But I get it with the following configuration:
> > > [ ... ]
> > > the following error message:
> > > [ ... ]
> > > hat jemand zufällig eine Idee woran das liegen könnte ? Ich bin nämlich langsam völlig ratlos.

> > Hi. OpenSlides 2.3 requires Python 3.6 or higher. Make sure that you have installed Python (>= 3.6) on your system. I would suggest testing version 2.2 or installing a more recent version of Python.

> @tsiegleauq thanks for the hint, so far I have come through first. One of the dependencies have caused me some problems. I am now at Python 3.7.

> Now it probably starts to migrate the DB but breaks off because a key is too long.
Is this due to the Secret Key which is in the Settings.py ? The DB of mine is still empty, I have done nothing at the system yet.
> [ ... ]
> I found the error myself, it was because the database was not converted to UTF8 .
Thanks again to the quick help, now the work with the tool can finally start. :)
