### ISSUE TITLE
version conflict with pytest 4.2.0

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#4243]
Travis failed if the lastest pytest 4.2.0 is installed:

```
$ python -W ignore -m pytest --cov --cov-fail-under=70
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/manager.py", line 267, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pytest 4.2.0 (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages), Requirement.parse('pytest!=4.2.0,>=3.6'))
```

Added hotfix 3d7b833eeb667e659827626437afd025abb8f6e3 by downgrading pytest to <4.2.0.

Wait for next pytest release (4.2.x).

**Comment by emanuelschuetze** [comment]
Already done in #4532
