### ISSUE TITLE
Delete statute paragrah failed (RuntimeError: SET_NULL_AND_AUTOUPDATE)

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#4405]
Try to delete a statute paragraph:

```
Internal Server Error: /rest/motions/statute-paragraph/1/
Traceback (most recent call last):
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/rest_framework/mixins.py", line 93, in destroy
    self.perform_destroy(instance)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/rest_framework/mixins.py", line 97, in perform_destroy
    instance.delete()
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/models.py", line 109, in delete
    return_value = super().delete(*args, **kwargs)  # type: ignore
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/db/models/base.py", line 879, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/home/emanuel/projects/openslides/src/OpenSlides/.venv/lib/python3.7/site-packages/django/db/models/deletion.py", line 221, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/home/emanuel/projects/openslides/src/OpenSlides/openslides/utils/models.py", line 168, in SET_NULL_AND_AUTOUPDATE
    "SET_NULL_AND_AUTOUPDATE is used in an invalid usecase. Please report the bug!"
RuntimeError: SET_NULL_AND_AUTOUPDATE is used in an invalid usecase. Please report the bug!
HTTP DELETE /rest/motions/statute-paragraph/1/ 500 [0.03, 127.0.0.1:40496]
```

**Comment by normanjaeckel** [comment]
Cannot reproduce (`HTTP DELETE /rest/motions/statute-paragraph/1/ 204 [0.06, 127.0.0.1:49810]`). I created a fresh db, added one statue paragraph and delete it.

**Comment by normanjaeckel** [comment]
@emanuelschuetze Anything to do for me here?

**Comment by emanuelschuetze** [comment]
Sorry, I cannot reproduce it any more...

**Comment by normanjaeckel** [comment]
You may reproduce it with a statute paragraph that has at least two motions (amendments) that refer to it.
