### ISSUE TITLE
Error: Message: Multiple users with same credentials!

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#6241]
I am not sure if this is an error of the client, the backend or the auth service. So I open it here. Please move it in the correct repo.

* I created a new meeting
* In this meeting I create a user with username "klaus" and password "pass".
* Then I delete this user
* Then I create a new user with the same name and password ("klaus", "pass").
* Then I try to login with this user.

The login fails with the error message: `Error: Message: Multiple users with same credentials!`.

In the server logs, there are the following error messages:

```
auth_1              | [03.10.2021 -- 16:24:37]: User object from datastore:  {
auth_1              |   '39': {
auth_1              |     username: 'd1',
auth_1              |     password: '7e125d2b12cfbe15e3a7709179bedba690212dc189376439f2fe2ad772b90358FJd1hJu+GwTsKkaOLpFm1QrhJikJuzr1ZRLZOoVedtV/X+Ov7prgv6WGG7roZ5rxYkOGv+L0t1+vm8mlMX0YHA==',
auth_1              |     id: 39,
auth_1              |     is_active: true
auth_1              |   },
auth_1              |   '40': {
auth_1              |     username: 'd1',
auth_1              |     password: '2395a91adb6ea6f13aea85251e1b3d9231edc68c67cdd926abed76b627ad1db8c7d6mcRBU3wxbNSA6e2L7sy/GIPxFrE66I2HjBDvrUYVJV5Gg3naWofC+nIXCV1YBcpUbVNpLzL4EjGl/rhyhg==',
auth_1              |     id: 40,
auth_1              |     is_active: true
auth_1              |   }
auth_1              | } 
auth_1              |  [03.10.2021 -- 16:24:37]: Multiple users found for same username! 
auth_1              | Stacktrace:
auth_1              |  AuthenticationException [Error]: Multiple users with same credentials!
auth_1              |     at new AuthenticationException (/app/src/core/exceptions/authentication-exception.ts:5:9)
auth_1              |     at UserService.<anonymous> (/app/src/api/services/user-service.ts:39:19)
auth_1              |     at Generator.next (<anonymous>)
auth_1              |     at fulfilled (/app/node_modules/tslib/tslib.js:114:62)
auth_1              |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
auth_1              |   statusCode: 403,
auth_1              |   title: 'Multiple users with same credentials!'
auth_1              | }
```

Please fix this issue as soon as possible, I blocks me from writing the performance-tool that @emanuelschuetze  needs.

**Comment by normanjaeckel** [comment]
Looks like that there are two bugs:

- Backend does not check username uniqueness: https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/action/actions/user/create.py

- Auth does not ignore deleted users.

**Comment by jsangmeister** [comment]
> * Backend does not check username uniqueness: https://github.com/OpenSlides/openslides-backend/blob/master/openslides_backend/action/actions/user/create.py

Yes it does, in the user mixin: https://github.com/OpenSlides/openslides-backend/blob/406f4127fb92ae33054abbee59c09e50bdcaf7d0/openslides_backend/action/actions/user/user_mixin.py#L25

I, too, would say that the issue is auth not ignoring deleted users.

**Comment by GabrielInTheWorld** [comment]
> I, too, would say that the issue is auth not ignoring deleted users.

That's right.
