### ISSUE TITLE
OS4-export: projector related errors

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/OpenSlides#6317]
## First
When topics are deleted but have been projected before, they are still referenced in the projector queue.
This will make the export fail.

**How to Reproduce**
on [nighty](https://nightly.demo.openslides.org):
1. Add two topics t1, t2 to agenda
2. Project t1, add t2 to Queue
3. delete t2
4. In Settings 'export to OS4'

Browser console shows:
```
polyfills.824c125….js:1 GET https://nightly.demo.openslides.org/apps/core/os4-export/ 400
main.de095a6….js:1 ERROR Error: Uncaught (in promise): Error: Unknown slide core/clock
    at O (polyfills.824c125….js:1)
    at polyfills.824c125….js:1
    at i (main.de095a6….js:1)
    at l (main.de095a6….js:1)
    at u.invoke (polyfills.824c125….js:1)
    at Object.onInvoke (main.de095a6….js:1)
    at u.invoke (polyfills.824c125….js:1)
    at e.run (polyfills.824c125….js:1)
    at polyfills.824c125….js:1
    at u.invokeTask (polyfills.824c125….js:1)
```

## Second
In weird cases the Browser console shows:
```
polyfills.824c125….js:1 GET https://nightly.demo.openslides.org/apps/core/os4-export/ 400
main.de095a6….js:1 ERROR Error: Uncaught (in promise): Error: Unknown slide core/clock
    at O (polyfills.824c125….js:1)
    at polyfills.824c125….js:1
    at i (main.de095a6….js:1)
    at l (main.de095a6….js:1)
    at u.invoke (polyfills.824c125….js:1)
    at Object.onInvoke (main.de095a6….js:1)
    at u.invoke (polyfills.824c125….js:1)
    at e.run (polyfills.824c125….js:1)
    at polyfills.824c125….js:1
    at u.invokeTask (polyfills.824c125….js:1)
```
**How to Reproduce**
on [nighty](https://nightly.demo.openslides.org):
1. Add one topic t1 to agenda
2. Project t1 then delete it from the Queue view in the projector (don't delete the actual topic)
3. In Settings 'export to OS4'

This seems minor though. As far as I can tell it only occurs when `First` is also already causing problems.

## Last
While investigating these errors, I came across https://github.com/OpenSlides/OpenSlides/blob/1e22ffbf7e4e2d9f410bca0d1eca14e3b7642d05/server/openslides/core/export.py#L1295 which I'm sure is a typo (should be `element` not `elements`) also sometimes causing the export to fail, with traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/app/openslides/utils/rest_api.py", line 136, in handle_exception
    return super().handle_exception(exc)  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc 
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/openslides/utils/views.py", line 32, in method_call
    return Response(self.get_context_data())
  File "/app/openslides/core/views.py", line 738, in get_context_data
    return OS4Exporter().get_data()
  File "/app/openslides/core/export.py", line 197, in get_data
    self.migrate_projectors()
  File "/app/openslides/core/export.py", line 1297, in migrate_projectors
    element, i + 1, "history", old["id"]
UnboundLocalError: local variable 'element' referenced before assignment
```
I managed to circumvent this by 'previous'-clicking the projector queue all the way to beginning, then 'next'-clicking all the way to end.

@GabrielInTheWorld , @jsangmeister , @reiterl , @r-peschke 
I'm not sure who of you could fix this the best.
For now I'll assign @reiterl

**Comment by reiterl** [comment]
Don't random assign me.

**Comment by jsangmeister** [comment]
Mmh, first and second look like another error to me: The slide type `core/clock` is not handled in the export. I assume you had the clock projected in your tests?

Unfortunately, I do not know enough about our projector system and the changes in OS4 to know how to handle this. The error is thrown here: https://github.com/OpenSlides/OpenSlides/blob/93e0b53b9e324b6b9a6c189f76fdb4549eee0dd7/server/openslides/core/export.py#L1358

since the collection type `core/clock` is not handled there. But it is handled here:
https://github.com/OpenSlides/OpenSlides/blob/93e0b53b9e324b6b9a6c189f76fdb4549eee0dd7/server/openslides/core/export.py#L1278

I don't know if that's enough and the error can just be ignored or if the slide has to be exported in another way. Maybe @tsiegleauq or @r-peschke can answer this?


Regarding the last error I agree with you, this looks like a simple typo, especially when looking at the lines above it.

**Comment by jsangmeister** [comment]
Looked further into it and it seems like this is a case of corrupt data where the countdown somehow got into the preview/history of the projector. I will simply ignore these cases since it should not really matter.

**Comment by jsangmeister** [comment]
done in #6327
